979 syllabus upload button change
BCStudentSoftwareDevTeam/celts pull request #1005
Opened 2023-07-14 20:03 UTC by ojmakinde

The upload button on the Course Proposal page has been updated. In the process of replacing it with the existing view in the Create Event page, the team decided it would be best to integrate the Create Event code into a function, and have it called wherever it is needed.

In the process of refactoring, certain parts of the function were optimized and condensed, improving readability and conciseness.

The function now exists in base.js, and is called in the CreateEvent.js and slcNewProposal.js files.

Code can be tested by uploading attachments in the Create Events page and the Course Proposals page.

Resolves #979

2023-07-17 13:55 UTC, BrianRamsay requested changes

2023-07-17 13:55 UTC, BrianRamsay commented on app/templates/serviceLearning/slcProposal.html
> +                              id={{eventData.id}}>
There is no `eventData` on this page.

2023-07-17 13:55 UTC, BrianRamsay commented on app/templates/serviceLearning/slcProposal.html
> +          <div class="form-group mb-5">
The existing file display is currently duplicated with events. It should be generalized as well, either as a separate template or a javascript implementation.

2023-07-17 13:55 UTC, BrianRamsay commented on app/templates/serviceLearning/slcProposal.html
> +          <div id="attachedObjectContainer" class="py-0 px-0"></div>
Let's go ahead and drop this `<div>` from the html, since it is really just a placeholder here. You can add it in the js.

2023-07-17 13:55 UTC, BrianRamsay commented on app/templates/serviceLearning/slcProposal.html
> +        <!--Additionally, we are going to get rid of (or modify) this filepaths condition here, as it is the old way of showing added attachments-->
Don't leave in old comments

2023-07-17 13:55 UTC, BrianRamsay commented on app/templates/serviceLearning/slcProposal.html
> +        <!--And finally, we are going to get rid of the modal in the other page-->
Remove working comments

2023-07-17 13:55 UTC, BrianRamsay commented on app/static/js/base.js
> +                                              </div>")
let's not indent this block so much, so the lines aren't as long

2023-07-18 20:18 UTC, ojmakinde commented
![](https://github.trello.services/images/mini-trello-icon.png) [Syllabus upload should be changed to match the new upload #979](https://trello.com/c/RVR3OXYt/646-syllabus-upload-should-be-changed-to-match-the-new-upload-979)

2023-07-19 20:36 UTC, BrianRamsay requested changes

2023-07-19 20:36 UTC, BrianRamsay commented on app/controllers/admin/routes.py
>  @admin_bp.route("/deleteEventFile", methods=["POST"])
Let's attach both of the delete routes to the same function, since they are doing the same thing.

2023-07-19 20:36 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +        return redirect('/serviceLearning/courseManagement')
There are two different course management pages they could have come in from, the admin one or the instructor one. We need to use the same method we use elsewhere to go back to the correct one.

2023-07-20 14:06 UTC, BrianRamsay approved these changes

2023-07-20 14:10 UTC, merged