Saving files for courses and events without duplication
BCStudentSoftwareDevTeam/celts pull request #1007
Opened 2023-07-17 20:01 UTC by michelmonc

Did:
-  Check where the attachment is being saved for a recursive event
- Create a function makeDirectory to create the directory when being called to avoid duplicate events and course
- Created a condition to call makeDirectory function and to savefiles
- Created a test to make sure that the file is created and is not duplicated
- Ran tests and all passed
- Remove Comments
- Added Comments

2023-07-17 20:18 UTC, BrianRamsay requested changes

2023-07-17 20:18 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +        # Passing if the error is 17
This comment isn't useful. I can tell that you are looking at error 17 from the code. But I can't tell what error 17 is.

2023-07-17 20:18 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +            # Perform additional error handling if needed
Remove this comment

2023-07-17 20:18 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +        # Creating the directory when call in saveFiles
Don't assume where this function will be called.

2023-07-17 20:18 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +        # Creating the directory when call in saveFiles
Also there should be a better description that describes what the function does and/or why it exists

2023-07-17 20:18 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +
remove the newline here. That will connect the pass to the except better, visually

2023-07-17 20:18 UTC, BrianRamsay commented on tests/code/test_fileHandler.py
> +        handledEventFile.makeDirectory()
You never actually test that the directory was created. Also, you aren't using the database, so you don't need to use a database transaction.

2023-07-18 13:49 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up empty directories for file attachments on recurring events. #972](https://trello.com/c/2MZBaj2L/642-clean-up-empty-directories-for-file-attachments-on-recurring-events-972)

2023-07-18 14:09 UTC, BrianRamsay requested changes

2023-07-18 14:09 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +        # Creating the directory when call in saveFiles
don't say "when called in saveFiles" in the comment. It doesn't matter to the function where it is called.

2023-07-18 14:09 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +                pass
This try/except is not doing what you want. You wanted it to ignore only error 17, but what you are doing is ignoring all `OSError` exceptions, and the conditional doesn't matter. You need to re-raise the exception if you don't want to catch it, not pass it.

2023-07-18 14:09 UTC, BrianRamsay commented on app/logic/fileHandler.py
> +                # Creating directory and save the file to the filesystem if 'saveFileToFilesystem' is True.
`saveFileToFilesystem` will never contain True. And the `if` part is obvious from the code, anyway. We don't want things in comments that are obvious from the code (unless they are more like structural comments). Comments are for organization and explaining the not obvious things.

2023-07-18 20:41 UTC, BrianRamsay requested changes

2023-07-18 20:41 UTC, BrianRamsay commented on tests/code/test_fileHandler.py
> +
We should make sure that the directory doesn't exist before we try making it, because otherwise we could be not creating it and we wouldn't know it.

2023-07-20 14:12 UTC, michelmonc commented
Resolve #972

2023-07-21 13:55 UTC, BrianRamsay approved these changes

2023-07-21 13:55 UTC, merged