999 training hover
BCStudentSoftwareDevTeam/celts pull request #1012
Opened 2023-07-25 17:19 UTC by hoerstl

Issue: Issue #999 asked us to create a view hover to show all relevant trainings for a program and whether a user had been to them next to each user entry in the track volunteers page. There is a matching view hover in each person's profile that should be duplicated into the track volunteer page when an event is in the future.

Solution: The example inside of the user profile page was perfect for getting the trainings for a single user but what we needed was the ability to get them for a whole list of users without making a query for each. Therefore, we had to change what the getUserParticipatedTrainingEvents function did. It now accepts a list of users and where it returned a list before, it now returns a dictionary with a key for each of the users and their corresponding list in a similar fashion. Now that the underlying function has been changed to fit the use case for both locations, we just used it to pass a new variable to the render_template which we use to create the same hover as is used inside of the user profile page. The hover's data-content is now retrieved via a snippet file holding a macro since it's the same in both spots. This filename is trainingsHoverMacro.html.

To Test: Create an event in the future that belongs to a particular program. For that program in the same academic year, create another event in the past and mark it as a training, then, add any volunteer to it. At this point, go back to the first event you created and manually rsvp (add) the person you added to the second event along with someone else. Ensure that the view hover appears for both of them. Now, ensure that one of the view hovers says that they attended the training and the other says that they did not. 
Another place to check would be the user profile page. Go to that page and ensure that the view hovers there are functional as well. Note that the view hovers on this page show all trainings that are offered in the same academic year as the current term that we've set in our cookies whereas the event page shows all trainings that are offered in the same academic year as the event's term so the two may differ in information if your term is set differently than the event.

2023-07-25 20:48 UTC, AndersonStettner requested changes

2023-07-25 20:48 UTC, AndersonStettner commented on app/logic/participants.py
> +    result = {}  # Beans- rename this dict
Rename the dict if you still want to or remove this comment.

2023-07-31 19:33 UTC, zachneill requested changes, later dismissed
thank you for title casing your branch. i really appreciate it

2023-07-31 19:33 UTC, zachneill commented on tests/code/test_participants.py
> +        # If the event has not occured yet, assert that someone who has rsvp'd is true and someone who hasn't is false
there's two r's in the word occurred lawrence

2023-07-31 19:33 UTC, zachneill commented on tests/code/test_participants.py
>              if (counter % 2) == 0:
this is literally python you don't need the parentheses around counter % 2

2023-08-01 19:09 UTC, BrianRamsay requested changes
By default, I see myself as not attending an All Celts Training that is tied to Adopt a Grandparent (from the profile View), but that training isn't in the current term. Trainings are only valid for the current term. All Volunteer Trainings are valid for the academic year. I think this may be correct in the View that is tied to an event, but not the View that is on the program in the profile. They should share data and rendering code.

2023-08-01 19:09 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +    allReleventUsers = [participant.user for participant in eventVolunteerData + eventNonAttendedData + eventWaitlistData]
we should spell 'relevant' correctly

2023-08-01 19:09 UTC, BrianRamsay commented on tests/code/test_participants.py
>              if (counter % 2) == 0:
It's an order of operations clarification. I'm ok with it.

2023-08-04 14:05 UTC, AndersonStettner requested changes

2023-08-04 14:05 UTC, AndersonStettner commented on app/templates/events/event_list.html
>                  <td class="text-dark">This event does not belong to any program.</td>
All Volunteer Training does belong to a program now that other CELTS is a program. Though, since All Volunteer is a required training for every program I think it might work to make this message something like "This is a required training for all programs."

2023-08-04 14:05 UTC, AndersonStettner commented on app/templates/events/trackVolunteers.html
> +                          <span class="bi bi-x-lg" aria-label="Did not complete all trainings."></span> &nbsp&nbsp
Set a variable for the label.

2023-08-04 14:05 UTC, AndersonStettner commented on app/templates/main/userProfile.html
> +                      <a class="trainingPopover" id="{{row.program.id}}" href="javascript:void(0);" data-toggle="popover" title="Program Trainings" data-content= "{{trainingsHover(trainingList)}}">Vi
Both of these hovers are exactly the same, what is the point of the condition?

2023-08-04 14:05 UTC, AndersonStettner commented on app/templates/trainingsHoverMacro.html
> +    <p>No trainings for this program.</p>
I think this should probably be something like "There are no trainings required for this program." or "This program has no required trainings."

2023-08-04 14:05 UTC, AndersonStettner commented on tests/code/test_userManagement.py
> +        NonOtherPrograms = Program.select().count() - 1 # - Other Celts-Sponsored
I do not like the variable name `NonOtherPrograms`. the first letter should not be capital and the comment suggests that this is for the other CELTS program so why is programs plural in the variable?

2023-08-04 14:23 UTC, AndersonStettner submitted a review, later dismissed
The `X` is not changing to a `check` despite the volunteer having attended the only training required for the event.

2023-08-04 20:54 UTC, hoerstl commented
The tests are broken because now that we've restricted what events the trainedParticipants function checks to see if you've attended, khatts has not attended an event for the current term (id=4). The tests in test_participants.py need to be completely rewritten to accommodate for this correct restriction in what that function returns. To recap, it checks to see if you've been to all program trainings offered within the current semester and all All Volunteer Trainings from the term's academic year.

2023-08-09 14:51 UTC, BrianRamsay approved these changes

2023-08-09 14:52 UTC, merged