992 emergency contact information
BCStudentSoftwareDevTeam/celts pull request #1022
Opened 2023-08-02 16:09 UTC by hoerstl

Issue #992 

Issue - This was an enhancement to create a new method to add an emergency contact as well as a user's insurance information to their profiles. This information should then be used to create a printout of the data so that it looks just like the form here: [https://github.com/BCStudentSoftwareDevTeam/celts/files/12028236/request.pdf](https://github.com/BCStudentSoftwareDevTeam/celts/files/12028236/request.pdf)

Solution - We created two data tables to store this information. The user profile now has a select on the top right which allows navigation to the three new pages we've created. One for Emergency Contact, another for Insurance Information, and finally another to print the form. 

To Test - Go to any user profile as the user who owns it. Now, open the 'Choose an Action' select and choose the options. Submit data to the emergency contact and insurance information pages. Now, got to 'Print Travel Form' and ensure that the form prompts you to print correctly with the information you've just filled in. Now go to another user's profile as someone else (e.x. neillz checking out ramsayb2's profile). Go to their edit contact info page and ensure that it's view only.

2023-08-02 18:50 UTC, zachneill requested changes
i get emails every time you git push plus another one from your github code coverage bot immediately afterwards. so ur next commits better be avengers-level threat good

2023-08-02 18:50 UTC, zachneill commented on app/controllers/main/routes.py
> +        readOnly = False if g.current_user.username == username else True
u can just do `readOnly = g.current_user.username != username`

it evaluates the way you want it to. the only problem is readability which tbh is a you problem

2023-08-02 18:50 UTC, zachneill commented on app/controllers/main/routes.py
> +                                readOnly = readOnly
the other parameters don't have   s p a c e s    b e t w e e n    t h e     e q u a l s     s i g n

2023-08-02 18:50 UTC, zachneill commented on app/controllers/main/routes.py
> +        readOnly = False if g.current_user.username == username else True
see previous comment

2023-08-02 18:50 UTC, zachneill commented on app/models/emergencyContact.py
> +from app.models import *
do you need this import?

2023-08-02 18:50 UTC, zachneill commented on app/static/css/travelForm.css
> +    margin-bottom: 0px;
if it's a 0 then you don't need to specify px, em, pt, etc...

2023-08-02 18:50 UTC, zachneill commented on app/static/css/travelForm.css
> +    font-size: 13px;
idk if your chad supervisors care but avoid using px for font-size. it poses a problem for accessibility. when a user changes their browser default font size, rem and em values change accordingly but px values stay the same

here's a reference. https://joshcollinsworth.com/blog/never-use-px-for-font-size

2023-08-02 18:50 UTC, zachneill commented on app/static/js/base.js
> +  var printProposal = window.open(path);
use let or const instead of var in this function

2023-08-02 18:50 UTC, zachneill commented on app/templates/main/emergencyContactInfo.html
> +<div id='username' hidden value='{{contactInfo.user}}'></div>
if you're using this hidden tag the way i think you are, change this from a div to an input tag. if nothing else, it's better practice

2023-08-02 18:50 UTC, zachneill commented on app/templates/main/emergencyContactInfo.html
> +    <div class='form-group' style='text-align:right'>
bootstrap class="text-end"

2023-08-02 18:50 UTC, zachneill commented on app/templates/main/insuranceInfo.html
> +<div id='username' hidden value='{{userInsuranceInfo.user}}'></div>
prob change to hidden input tag

2023-08-02 18:50 UTC, zachneill commented on app/templates/main/travelForm.html
> +    <!-- {% set lineCharLength = 87 %}
take this out if ur not using it. totally ruined the moment

2023-08-03 15:52 UTC, hoerstl commented on app/models/emergencyContact.py
> +from app.models import *
yeah, we need baseModel from the app models so we can inherit from it.

2023-08-04 14:44 UTC, AndersonStettner requested changes
We should improve our email validation:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/38d9f6dd-945a-4ffe-94f2-1cb13efc3147)

2023-08-04 15:00 UTC, AndersonStettner requested changes
We should be more specific with the ids of the emergency contact info and insurance info. 

We might want to add an 'inputmask()` to the phone numbers on the emergency contact info page and. 

Also, did yall look into changing the logo that is used on the travel form print? If you decide to stick with the current logo that is fine but we should get a better screen grab so that we are not cutting off part of the "s" in CELTS.

2023-08-04 15:00 UTC, AndersonStettner commented on app/static/css/travelForm.css
> +    font-size: 13px;
In this case it should be fine since this is a css file to print out or download a pdf of a travel form and the only time they will see the page is when they are printing or downloading the form.

2023-08-04 15:00 UTC, AndersonStettner commented on app/templates/main/emergencyContactInfo.html
> +            <a id='exit' href='/profile/{{username}}' class='btn btn-secondary'>Cancel</a>
Cancel should be left aligned.

2023-08-04 15:00 UTC, AndersonStettner commented on app/templates/main/insuranceInfo.html
> +            <a id='exit' href='/profile/{{username}}' class='btn btn-secondary'>Cancel</a>
Cancel should be left aligned.

2023-08-07 15:22 UTC, merged