Clean student managers
BCStudentSoftwareDevTeam/celts pull request #1095
Opened 2023-10-20 12:17 UTC by andersoncedu

Issue:
There was an issue where student staff retained their program manager roles when they were removed from student staff.

Fix:
To fix this issue, the query was updated to remove program managers when students were removed from student staff.

Test:
To test this issue, navigate to admin - settings from the sidebar on the left and remove students from student staff roles, this should also remove them from student manager roles which can be verified by navigating to the students profile by using the student search and clicking the program manager accordion tab.

2023-10-20 13:05 UTC, andersoncedu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Student staff retain their program management roles on events even after being removed as student staff #957](https://trello.com/c/TYjpBQZY/640-student-staff-retain-their-program-management-roles-on-events-even-after-being-removed-as-student-staff-957)

2023-10-24 16:51 UTC, ojmakinde commented
Tested extensively. Works perfectly.

2023-10-24 19:45 UTC, qasema requested changes
add test cases for the new updates of the removeCeltsStudentStaff function.

2023-10-31 14:36 UTC, AndersonStettner approved these changes

2023-10-31 14:38 UTC, merged