Minor page 989
BCStudentSoftwareDevTeam/celts pull request #1096
Opened 2023-10-24 02:56 UTC by bledsoef

2023-11-29 20:06 UTC, qasema commented
I think the page design could be a bit better. I would say try to group related elements together.

2023-11-29 20:30 UTC, qasema requested changes
both accordions are initially open but the content is not displayed. I would say have the first accordion open or have them both closed

2023-11-30 22:18 UTC, bledsoef commented
> both accordions are initially open but the content is not displayed. I would say have the first accordion open or have them both closed

Fixed.

2023-11-30 22:19 UTC, bledsoef commented
> I think the page design could be a bit better. I would say try to group related elements together.

Gave the page a little bit of a redesign

2023-12-01 00:30 UTC, qasema requested changes
<img width="503" alt="Screenshot 2023-11-30 at 7 26 48 PM" src="https://github.com/BCStudentSoftwareDevTeam/celts/assets/68142980/7ede3db6-9d6b-45da-a7df-6ea0c6fe2aba">

Checkbox alignment is off. Try changing the page size to test it

2023-12-01 00:34 UTC, qasema commented on app/controllers/minor/routes.py
> +from app.models.course import Course
Is Course going to be used later?

2023-12-01 00:36 UTC, qasema commented on app/controllers/minor/routes.py
> +from playhouse.shortcuts import model_to_dict
same with model_to_dict

2023-12-01 00:45 UTC, qasema commented on app/controllers/minor/routes.py
> +    return information
I think there could be a case where the student does not have engagement. In that case, we should return something indicating that. But you can handle that in the front end by checking if information is empty

2023-12-01 00:54 UTC, qasema requested changes
We should also add an extra layer of validation for the current user in the controllers. Now everyone can view anyone else's minor page

2023-12-01 18:03 UTC, bledsoef commented on app/controllers/minor/routes.py
> +    return information
Brian had let me know that I just shouldn't display anything if they have nothing

2023-12-01 22:14 UTC, qasema commented
looks good to me

2023-12-01 22:16 UTC, qasema approved these changes, later dismissed

2023-12-06 18:40 UTC, BrianRamsay requested changes
click for more information should open in a new window

community engagement ui feedback
- highlight and click on the whole row, not just links
- links out to the event page should open in a new window (`target="_blank"`)
- include Course abbreviation with course name
- Remove "Information" from course info header
- Program event list should include hours for each event, and the total for the program

2023-12-06 18:40 UTC, BrianRamsay commented on app/controllers/minor/routes.py
> +    if not (g.current_user.isCeltsAdmin or g.current_user.isCeltsStudentStaff):
use isAdmin if you want both cases (we'll figure out the exact permissions needed later)

2023-12-06 18:40 UTC, BrianRamsay commented on app/controllers/minor/routes.py
> +@minor_bp. route('/cceMinor/<username>/requestOtherCommunityEngagement', methods=['GET,POST'])
no space

2023-12-06 18:40 UTC, BrianRamsay commented on app/logic/minor.py
> +    courseInformation = {"instructors": [(instructor.user.firstName + " " + instructor.user.lastName) for instructor in courseInstructors], "course": course}
This will be doing a separate query for each instructor. Join User in the query.

2023-12-06 18:40 UTC, BrianRamsay commented on app/logic/minor.py
> +                       .group_by(Event.program, Event.term))
Anderson doesn't like the query indentation. Line up your periods.

2023-12-06 18:40 UTC, BrianRamsay commented on app/logic/minor.py
> +                               .join(Program, JOIN.LEFT_OUTER).switch()
left join not needed, as the where clause prevents the null case anyway

2023-12-06 18:40 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +        {% if g.current_user.isCeltsAdmin or g.current_user.isCeltsStudentStaff %}
is `isAdmin` to cover both cases

2023-12-08 17:56 UTC, gahimbaref commented
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89202583/88dcc98d-fdf2-451f-b09e-864356cc0c61)

clicking on the checkboxes doesn't seem to be doing anything unless you click the activity name, is there a reason for the checkboxes?

2023-12-08 17:57 UTC, bledsoef commented
> ![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89202583/88dcc98d-fdf2-451f-b09e-864356cc0c61)
> 
> 
> 
> clicking on the checkboxes doesn't seem to be doing anything unless you click the activity name, is there a reason for the checkboxes? 

That functionality is part of a different issue

2023-12-08 18:02 UTC, gahimbaref commented
Centering the title "Zach Neill's CCE Minor" might look a bit better, it would also be consistent with the other pages

2023-12-12 18:39 UTC, bledsoef commented
> Centering the title "Zach Neill's CCE Minor" might look a bit better, it would also be consistent with the other pages

I was basing this off of the user profile which has its title aligned to the left.

2023-12-12 20:37 UTC, BrianRamsay approved these changes

2023-12-12 20:37 UTC, merged