Volunteer Remove RSVP Error
BCStudentSoftwareDevTeam/celts pull request #110
Opened 2021-09-07 14:36 UTC by sreynit02

This PR fixes issue #105 : The remove rsvp button was not working: gave an error and did not update in the database.

Fixed: imported the missing models and libraries and added a deletion functionality.

Test:
Log in as a student and navigate to /events/current and RVSP for an event by clicking on the RSVP button. Check the database in the eventParticipant table and it should create an entry for that event. Then, remove rsvp for that same event and get the eventParticipant table again. The previous entry should be removed.

2021-09-07 17:03 UTC, bryantal approved these changes, later dismissed

2021-09-07 17:18 UTC, BrianRamsay requested changes

2021-09-07 17:18 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +    currentEventParticipant.delete_instance(recursive=True)
I doubt you want `recursive=True` here.

2021-09-09 14:18 UTC, sreynit02 commented on app/controllers/main/routes.py
> +    currentEventParticipant.delete_instance(recursive=True)
removed

2021-09-14 17:31 UTC, BrianRamsay submitted a review, later dismissed

2021-09-14 17:32 UTC, merged