Request other community engagement
BCStudentSoftwareDevTeam/celts pull request #1103
Opened 2023-11-17 21:27 UTC by azabeli

Issue:  Create a basic form that a student will fill in to request an experience completed outside of the college. The page should include: the student's name, the name of the position they worked/volunteered for, total hours they worked/volunteered, the total weeks they worked/volunteered, description of the work, term the experience is going to be credited in,  and a place to upload a file from a supervisor that verifies the student did work/volunteer the amount they said. It should also have 3 statuses associated with an "Other" engagement.  

Fix: We created and rendered the page with the name of the student and a form to fill in other information like:  the name of the position they worked/volunteered for, total hours they worked/volunteered, the total weeks they worked/volunteered, description of the work,  and we also created a place to upload a file from a supervisor that verifies the student did work/volunteer the amount of hours they mentioned. We are still fixing the term the experience is going to be credited in and the  3 statuses associated with an "Other" engagement.  
 

Test: load the following route to see the page: http://127.0.0.1:8080/cceMinor/<username>/requestOtherCommunityEngagement

resolving issue #990

2023-12-04 22:57 UTC, gahimbaref reviewed
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89202583/abe98172-03d2-4d17-be2f-f9bcc0533ba9)

- "Other Credit" could be made a bit more descriptive 
-  a user can input anything in the hours field, I think it should be limited to numbers (not letters)
- company/organization box seems a little out of place 
- Not sure the difference between Activity vs Activity/Service, they are 2 different fields)

2023-12-04 22:57 UTC, gahimbaref commented on app/controllers/minor/routes.py
> +    # filepaths = handleFileSelection()
remove unused code

2023-12-04 22:58 UTC, gahimbaref commented
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89202583/5283c10d-9f05-4358-adcd-eaacd94a2338)

It says page not found after submitting the form `Send Other Request`

2023-12-12 21:32 UTC, andersoncedu commented
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/97543993/9abec339-0b76-41d2-9892-38e726d877df)

There might be a problem here.

2024-01-16 21:40 UTC, BrianRamsay requested changes

2024-01-16 21:40 UTC, BrianRamsay commented on app/models/otherExperience.py
> +class OtherExperience(baseModel):
Add 'CCE' to the name somewhere

2024-01-16 21:40 UTC, BrianRamsay commented on app/models/otherExperience.py
> +    service = CharField()
'description' is probably a better name for this, and matches what you have in the UI

2024-01-23 20:19 UTC, closed without merging