624 service learning refactor
BCStudentSoftwareDevTeam/celts pull request #1127
Opened 2024-02-08 18:34 UTC by azabeli

resolves #624

2024-02-28 18:14 UTC, AndersonStettner requested changes, later dismissed
Please fix the formatting on all the queries you added typing to. 

I encountered the following error when trying to create a new SLC Proposal: 
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/4c0a74db-c0db-4174-b94e-36fb3879414f)

I created the course as `Brian Ramsay` with `Scott Heggen` as the `Faculty`, I filled in all the asked for data in the left column, uploaded an attachment, and tried to go to the `questions` page and then got that error. The course was successfully created but I get the same error every time I attempt to `View` or `Edit` the Proposal.

2024-02-28 18:14 UTC, AndersonStettner commented on app/controllers/serviceLearning/routes.py
> +@serviceLearning_bp.route('/serviceLearning/courseManagement', methods = ['GET']) # maybe we refactor to remove
Is this comment a leftover TODO or something else?

2024-02-28 18:14 UTC, AndersonStettner commented on app/controllers/serviceLearning/routes.py
> +    instructors_data=course.courseInstructors
This should be camelCase, `instructorsData`, to be in line with variable naming throughout the application.

2024-02-28 18:14 UTC, AndersonStettner commented on app/logic/serviceLearningCourses.py
>                       .order_by(Course.term.desc(), Course.status))
Please fix the formatting on this query.

2024-02-28 18:14 UTC, AndersonStettner commented on app/logic/serviceLearningCourses.py
> +
Please fix the formatting on the query.

2024-02-28 18:14 UTC, AndersonStettner commented on app/logic/serviceLearningCourses.py
> +    result: DefaultDict[User, str] = defaultdict(list)
It might be good to rename `result` to what it actually represents

2024-02-28 18:14 UTC, AndersonStettner commented on tests/code/test_serviceLearningCourses.py
> +
Please fix the formatting on the `Course.create`

2024-02-28 18:14 UTC, AndersonStettner commented on app/templates/serviceLearning/slcQuestionnaire.html
> +  <textarea id="slcQuestionOne" class="form-control textarea" aria-label="With textarea" name="1" aria-required="true">{{questionanswers[0]|urlize if isViewSlc else questionanswers[0] if questionansw
The questions should not be required.

2024-03-14 20:22 UTC, hoerstl submitted a review, later dismissed
Overall, I think that while we're moving forward with our code I'm not sure if we should do many variable annotations because a lot of these make it harder to actually read. I like the function annotations but I think naming the variables might be a tad overkill

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +        termObj: Term = Term.get_or_none(description = term) or addPastTerm(term)
Why not type this one Union[Term, None]?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +        courseInstructors: List[CourseInstructor] = list(CourseInstructor.select(CourseInstructor, User).join(User).where(CourseInstructor.course==course))
This annotation seems a bit much

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +            courseObj = Course.get_or_create(
Annotation for termObj on line 54 but no annotation for courseObj on this line?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +def unapprovedCourses(termId: int) -> List[Course]:
We could use a couple newlines in between function definitions

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +    return instructorToCoursesMap
I like how you've altered this function to use a defaultdict instead of the setdefault method on a dictionary object in this function, however, this function should probably not return a default dict and should instead cast it back to a dict object. Remember to change the annotation.

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +    course = Course.create(status=CourseStatus.IN_PROGRESS, createdBy=creator)
No annotation?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +def updateCourse(courseData, attachments=None):
Annotation?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +            course = Course.get_by_id(courseData['courseID'])
Annotation?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +            instructorList = []
Annotation?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +                instructorList = courseData.getlist('instructor[]')
Annotation?

2024-03-14 20:22 UTC, hoerstl commented on app/logic/serviceLearningCourses.py
> +                addFile= FileHandler(attachments, courseId=course.id)
I know this isn't you guys but while you're here annotating this line, wanna put a space before the equals sign?

2024-03-14 20:22 UTC, hoerstl commented on app/templates/serviceLearning/slcNewProposal.html
> +       {% if g.current_user.isCeltsAdmin %}
The formatting worked better here before you added the space

2024-03-15 17:23 UTC, Karina-Agliullova submitted a review, later dismissed
Looks good! Changes made make the code clean. Good work!

2024-03-18 18:02 UTC, merged