Updated sidebar display to show unapproved courses and interested students
BCStudentSoftwareDevTeam/celts pull request #1154
Opened 2024-03-13 18:35 UTC by bledsoef

## Issue
Fixes issue #1146 and issue #1147 

We were wanting to the admin to be able to see important information like courses they need to approve and students who expressed interest since those require their action. 

## Changes
- Created two new controllers, one in `admin/routes.py` and one in `admin/minor.py`
     - `getUnapprovedCoursesCount` gets all of the unapproved courses for the current term to display in the sidebar.
     - `getInterestedStudentsCount` gets all of the students who expressed interest in the CCE minor.
- Created a new JavaScript file `sidebar.js` that calls the two ajax requests on sidebar load and adds the numbers to the sidebar if applicable.
- Modified `sidebar.html` to include the new script and gave the Course Management and Minor Management tabs an id to be referenced by the JavaScript script.

2024-03-16 07:34 UTC, zachneill requested changes, later dismissed
urgent.

2024-03-16 07:34 UTC, zachneill commented on app/static/js/sidebar.js
> +    // fetch the number of interested students and display them  in the sidebar if there are any
there's an extra space here. dont you dare let this slide lawrence

2024-03-25 14:04 UTC, andersoncedu commented
Should the admin tab also show 'Admin (5)' ? This would let the admin know that there are items that need addressed in the admin tab.

2024-03-25 14:11 UTC, andersoncedu commented
Additionally, I think it might be more noticeable if there was a color change when there was something requested or a box or something. Otherwise, the issue looks good.

2024-03-25 14:15 UTC, andersoncedu commented
Without context, the numbers don't look like things that need to be addressed; they just look like numbers randomly on the page, in my opinion.

2024-03-25 15:12 UTC, stevensonmichel commented on app/controllers/admin/minor.py
> +    interestedStudentsCount: int = len(getMinorInterest())
I am not sure about the reason of int in that line, given that len always return an integer.

2024-03-27 15:14 UTC, bledsoef commented on app/controllers/admin/minor.py
> +    interestedStudentsCount: int = len(getMinorInterest())
It is the type of the variable. I have just been trying to type my variables for better readability.

2024-03-27 15:16 UTC, bledsoef commented
@andersoncedu In response to your comments, I should have commented this here but Brian and Anderson's suggestion was a hover to show more detail about the numbers. Otherwise since there are only a handful of admins and this will be demoed for them having it explicitly stated what the numbers are isn't super important.

2024-04-03 16:51 UTC, bledsoef commented
![](https://github.trello.services/images/mini-trello-icon.png) [Let Admin see the amount of unapproved courses they have in the sidebar](https://trello.com/c/IKOp7eSs/737-let-admin-see-the-amount-of-unapproved-courses-they-have-in-the-sidebar)

2024-04-03 16:52 UTC, bledsoef commented
![](https://github.trello.services/images/mini-trello-icon.png) [Display the amount of interested minor students in the sidebar](https://trello.com/c/Vb0E4ikc/142-display-the-amount-of-interested-minor-students-in-the-sidebar)

2024-04-04 20:56 UTC, Karina-Agliullova approved these changes
Good work!

2024-04-04 20:56 UTC, gahimbaref approved these changes
Looks good to me:)

2024-04-04 20:57 UTC, gahimbaref commented
> Additionally, I think it might be more noticeable if there was a color change when there was something requested or a box or something. Otherwise, the issue looks good.

I think a color might not be necessary. Having the numbers there seems to be sufficient

2024-04-04 21:07 UTC, merged