1151 other community experience rework
BCStudentSoftwareDevTeam/celts pull request #1184
Opened 2024-04-30 20:09 UTC by hoerstl

Resolves #1151

## Issue
In order to request an 'other' experience (for one of four experiences you need to finish the CELTS minor), you need to fill out a specialized form which takes in the following information:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89316750/ac03e920-dc01-4283-bbc2-88680f869b96)
The previous state of the form didn't have all of these fields.

## Solution
We added more fields that are error-checked and address all of the fields listed in the image.

## To Test
- Load up celts and reset database `from-backup`
- Navigate Admin Minor Management
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/89316750/fe06945a-5ac3-47fa-8c4b-8cb1a16e84a0)
- Ensure that each criterion that is mentioned in the above image is requested on the form.
- Ensure that you can't put any erroneous data into email or phone number fields
- Ensure that when saved, all relevant form data is saved into the `communityengagementrequest` database table.

2024-05-01 13:58 UTC, hoerstl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change the Request Other Community Engaged Experience form](https://trello.com/c/ThkN58Ob/741-change-the-request-other-community-engaged-experience-form)

2024-05-01 18:32 UTC, AndersonStettner requested changes

2024-05-01 18:32 UTC, AndersonStettner commented on app/templates/minor/requestOtherEngagement.html
> +        <label class="form-label" for="inputTerm"> <strong>Term:</strong> </label>
Term is the only label with a `:` so please remove it from Term or add it to the other labels

2024-05-01 18:38 UTC, AndersonStettner commented
I only had the one requested change but I have two other request that would not be a blocker to merger: 

1. I think I would prefer `(from supervisor)` to be capitalized next to `UploadConfirmation of Participation` 
2. I would like different sections to be spaced out a little bit more (space between `Experience Title` and `Company/Organization Information` etc..) because it feels a little cluttered to me. 

It could just be me though, again not blockers, just opinions.

2024-05-02 20:17 UTC, AndersonStettner approved these changes

2024-05-02 20:17 UTC, merged