Added my name in contributers
BCStudentSoftwareDevTeam/celts pull request #1195
Opened 2024-06-11 14:55 UTC by dixita9

I have added my name in the list of contributers

2024-06-11 14:57 UTC, BrianRamsay requested changes

2024-06-11 14:57 UTC, BrianRamsay commented on app/config/default.yml
> +  - name: "Anpriya Dixit"
You probably want "Anupriya"

2024-06-11 14:57 UTC, BrianRamsay commented on README.md
> +# Hi this is Anupriya
Not necessary in the README

2024-06-11 15:11 UTC, dixita9 commented on README.md
> +# Hi this is Anupriya
I have removed this from README

2024-06-11 15:12 UTC, dixita9 commented on app/config/default.yml
> +  - name: "Anpriya Dixit"
I have corrected the spelling!

2024-06-11 15:12 UTC, BrianRamsay requested changes
You have some merge conflicts to resolve.

2024-06-18 19:55 UTC, BrianRamsay commented
Added contributors in another PR

2024-06-18 19:55 UTC, closed without merging