fixed date past rendering issue
BCStudentSoftwareDevTeam/celts pull request #1211
Opened 2024-06-13 12:47 UTC by ali-ramazani

There was an issue in the isPast property which was responsible for displaying a box with the text "Event already passed". We figured out that the property was returning True or False only based on current time comparison with start time of the event. To fix this, we compared current time with end date of the event.

2024-06-13 12:51 UTC, CollegeStevenLN commented
For the property eventPast, it was defined by being greater than the start date and time. Logically, the event has only already pasted when the current time is greater than the end date and time.

2024-06-13 14:41 UTC, ali-ramazani commented
We noticed a build error after changing the logic of the isPast Event property. To fix the issue, we added a new property with the new logic.

2024-06-13 16:13 UTC, BrianRamsay requested changes
It is hard to review this as I have no idea what issue you are addressing. There's no issue linked to the PR, and I can't find a Trello card in PRs Ready for Review for this one either.

2024-06-13 16:13 UTC, BrianRamsay commented on app/models/event.py
> +        return datetime.now() >= datetime.combine(self.endDate, self.timeEnd)
We definitely don't want two different properties that seem like they do the same thing. You either need to rename them to make the distinction clear or replace the existing one with the new logic (if we are needing that everywhere).

2024-06-14 14:54 UTC, CollegeStevenLN commented on app/models/event.py
> +        return datetime.now() >= datetime.combine(self.endDate, self.timeEnd)
I renamed them to make a much clearer distinction. Also, we needed to change some of the logic. From our understanding, much of the logic could stay the same

2024-06-14 14:55 UTC, BrianRamsay requested changes

2024-06-14 14:55 UTC, BrianRamsay commented on tests/code/test_events.py
> +    assert event.isPastEnd
We should beef up this test a little bit. Testing for the negative cases, and where an event has started and not finished yet.

2024-06-14 14:57 UTC, ali-ramazani commented
There were 4 variables with very identical names, which made understanding the code harder. We refactored the whole codebase and only used 2 variables to make the event time more intuitive. Specifically, we are using isPastStart and isPastEnd to refer to the start and end of an event in the past.

2024-06-18 21:08 UTC, BrianRamsay approved these changes

2024-06-18 21:08 UTC, merged