Enhanced 'import_users.py' script using logging module
BCStudentSoftwareDevTeam/celts pull request #1240
Opened 2024-06-24 19:12 UTC by ali-ramazani

We enhanced the `import_users.py` script by integrating Python's logging module to provide detailed and descriptive log messages. These improvements will make the `cron.log` file significantly more informative, aiding in monitoring the script's execution and diagnosing any issues that arise from crontab scheduled tasks.

2024-06-24 19:22 UTC, Ndiayem14 commented
We have upgraded the `import_users.py` script by incorporating Python's logging module to generate comprehensive and detailed log messages. This enhancement will make the `cron.log` file much more insightful, facilitating better monitoring of the script's performance and easier troubleshooting of any issues that emerge from the crontab-scheduled tasks.

2024-07-03 18:00 UTC, CollegeStevenLN commented
This PR seemed to be pretty straightforward. I saw obvious problems with the logging, and I ran unit testing for this. This was not client side, so I saw no need to try to break it on that end. I would approve this PR.

2024-09-06 03:44 UTC, bledsoef commented
This fixes issue #1053

2024-09-11 19:33 UTC, vungc commented
Can you resolve the merge conflicts that exist? @ali-ramazani

2024-09-11 19:45 UTC, vungc requested changes, later dismissed
Need to resolve merge conflicts.

2024-11-08 14:48 UTC, hoerstl commented
I was running this in a devcontainer and I couldn't check this script with tracy but I looked over it and everything looks to be good. Let's give this one final run before we merge it.

2024-11-08 21:45 UTC, WackyWeaver reviewed
I approve it, but I would also want someone to try running it with TRACY locally.

2024-11-14 16:38 UTC, BrianRamsay reviewed
Based on https://docs.python.org/3/library/logging.html#levels, the log levels should be better defined. Log level DEBUG should show all of the output, INFO should give a summary of what the script did (count of users updated/inserted, etc), and WARNING should be when something unexpected happens, or we can't match a user.

We should be able to control the log levels in an argument to the script.

The output should go to stdout, not to a file. Let crontab control where the output goes.

2024-12-23 16:55 UTC, BrianRamsay submitted a review, later dismissed
It doesn't seem like there's an intermediate level of detail, but maybe that's because the first updates don't work right now. For ldap at least I either get only errors, or all of the info output.

2024-12-23 16:55 UTC, BrianRamsay commented on app/scripts/import_users.py
> +            userAdded += 1
You're using `userAdded` in the loops, but the variable is initialized as `usersAdded`

2024-12-24 15:19 UTC, stevensonmichel commented on app/scripts/import_users.py
> +            userAdded += 1
Fixed

2025-01-17 20:33 UTC, hoerstl approved these changes, later dismissed
I've fully tested the changes I made to the dockerfile and the logging code works perfectly.

2025-01-17 20:33 UTC, hoerstl commented on .devcontainer/Dockerfile
> +\nSetup=/usr/lib/x86_64-linux-gnu/odbc/libtdsS.so' >> /etc/odbcinst.ini"
I couldn't find a way to break this into two lines while keeping the indentation style so we're just going to have to live with it.

2025-04-16 15:27 UTC, BrianRamsay approved these changes
made some changes. let's goooo

2025-04-16 15:28 UTC, merged