Added full name to emergency contact updates as well as insurance updates in admin logs (updated)
BCStudentSoftwareDevTeam/celts pull request #1247
Opened 2024-06-26 20:40 UTC by JohnCox2211

No more duplicates allowed in DB for emergency contacts and insurance info. They are also  properly
displayed when changed in the admin logs now.

2024-06-26 20:48 UTC, JohnCox2211 commented
This issue is a continuation and fix for merge errors that broke this fix:  https://github.com/BCStudentSoftwareDevTeam/celts/pull/1212

2024-07-02 15:35 UTC, CollegeStevenLN commented on app/controllers/main/routes.py
> +###############################EMERGENCY CONTACT######################################
This seemed to be for finding where you were working in the page. It's much different than the other comments throughout. Maybe have just one #

2024-07-02 15:39 UTC, CollegeStevenLN commented on app/controllers/main/routes.py
> +###############################INSURANCE INFO######################################
same here

2024-07-17 14:20 UTC, esw0624 commented
I believe this is ready for a merge.

2024-07-17 14:50 UTC, BrianRamsay requested changes
contactInfo will be empty if there is no emergency contact for that user yet (which will fail later when we create the activity log)
Logic for when to create the contact info doesn't work

2024-07-18 20:38 UTC, closed without merging

2024-07-18 20:38 UTC, esw0624 commented
Made a new branch for this issue, so closing this branch and PR.