Redesign the display for uploaded files in events and courses | Eun Sung & Mahak
BCStudentSoftwareDevTeam/celts pull request #1249
Opened 2024-06-27 18:23 UTC by esw0624

1. Redesigned the display for the files in the View & Edit Event tabs by adding an Icon for the specific files the user uploaded.
2. Got rid of the Check Box for all the files other than image files in the Edit Event tab. 
3. Added padding to the margin so the Icon and file are not too close to each other for better display and visibility to the user.

2024-06-27 20:07 UTC, BrianRamsay requested changes
almost!

2024-06-27 20:07 UTC, BrianRamsay commented on app/static/css/base.css
> +  margin-right: 100px; /* Adjust the value as needed */
We don't use this class anywhere.

2024-06-27 20:12 UTC, esw0624 commented on app/static/css/base.css
> +  margin-right: 100px; /* Adjust the value as needed */
Done!

2024-07-01 15:57 UTC, BrianRamsay approved these changes

2024-07-01 15:57 UTC, merged