Added Contributors page
BCStudentSoftwareDevTeam/celts pull request #125
Opened 2021-09-22 15:15 UTC by Ebenezer997

Created  HTML file for the contributor page. We follow the format of the LSF contributors page. We added contributors to the default .yml file call the contributors from there.
To test, click on the student software development team link on the footer.

2021-09-22 16:52 UTC, BrianRamsay requested changes

2021-09-22 16:52 UTC, BrianRamsay commented on app/config/default.yml
> +contributors:
We should add Will Romano, and also any of the folks who worked on the Balsamiq mockups last year.

2021-09-22 16:52 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +    return render_template("/Contributors.html",
the name of this file should be lower-case, like all of our other templates

2021-09-22 16:52 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +           cfg = contribs
You don't need to pass this into the page. The application config is available to templates https://stackoverflow.com/questions/7104198/flask-accessing-the-config-variable-in-the-template

2021-09-22 16:52 UTC, BrianRamsay commented on app/templates/Contributors.html
> +{% set currentPage = "contributors" %}
Is this variable used? It's declared after base.html is included, and not used in your app_content block.

2021-09-27 14:53 UTC, Ebenezer997 commented
Fixed PR issuess

2021-09-28 13:45 UTC, BrianRamsay requested changes
Looks good, just one change.

2021-09-28 13:45 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +           # cfg = contribs
don't just leave it commented out. It's not useful anymore, and if someone really wants to see what it used to be they can look at the history of the file.

2021-09-28 18:49 UTC, BrianRamsay approved these changes
Looks good, thanks.

2021-09-28 18:49 UTC, merged