Create Events Page: Split the toggle buttons into 2 sections, and make one of 3 toggles required
BCStudentSoftwareDevTeam/celts pull request #1296
Opened 2024-07-24 20:35 UTC by JohnCox2211

The Bonners toggle will automatically toggle for Bonner events, but can be changed by the user if they wish and other event types can also use this toggle. The toggle state is saved between create event and edit event. The toggles are divided as requested into required and optional categories as well.

2024-07-24 20:36 UTC, JohnCox2211 commented
https://github.com/BCStudentSoftwareDevTeam/celts/issues/1294 - github issue

https://trello.com/c/50TXOdHE - trello card

2024-07-25 14:49 UTC, BrianRamsay requested changes
The bonner toggle only should be there for Bonner events.

Let's clean up the html classes and styles and try and simplify what controls the width of the components. Use the bootstrap grid only, if possible, for rows and columns.

2024-07-25 18:41 UTC, BrianRamsay requested changes
Let's clean up the css so we are relying more on bootstrap. the cutoff point should be xl, then you don't need min-width or the @media selector

2024-07-25 18:41 UTC, BrianRamsay commented on app/static/js/createEvents.js
> +    $("#checkIsTraining, #checkServiceHours, #checkBonners").not($target).prop('checked', false);
we can just use `$(event.target)` in the `not()`

2024-07-25 18:57 UTC, BrianRamsay approved these changes

2024-07-25 18:57 UTC, merged