Interface graduation management (Draft)
BCStudentSoftwareDevTeam/celts pull request #1355
Opened 2024-10-25 19:20 UTC by thealphagurlux

## Issue Description

Fixes #1315 
- Add issue description
- The purpose of this issue is to create a page that allows celts admins to mark students as graduated in the data base.

- The page should include a way for the user to filter students by searching for individual users, by Bonner Cohort (and what academic year they are associated with), as well as students who are participating in the CCE minor (whether they have completed it or made any progress towards it. ).

-

## Changes

- Use bullet points to provide a description of added changes.
- Add images, where possible, to provide more context to your changes.

## Testing

- Use `backticks` to highlight shell commands or file directories in your test descriptions.
- Use bullet points to provide a concise description of testing procedure.

2025-01-08 20:50 UTC, WackyWeaver requested changes, later dismissed
Almost to the finish line! I just had a few immediate changes I thought would be necessary, and there were one or typos I saw. I think that the flash messages still need to be handled, but otherwise, I'm excited to see this merged!

2025-01-08 20:50 UTC, WackyWeaver commented on app/controllers/admin/graduationManagement.py
> +def hasGraduated(username):
The "has" at the beginning of the function was a bit confusing, because it is an attributing verb. I usually associate it with a check, like "isDead" or "hasDied". Maybe change this use a better helping verb like "setGraduationStatus" or something similar.

2025-01-08 20:50 UTC, WackyWeaver commented on app/controllers/admin/graduationManagement.py
> +def hasNotGraduated(username):
same here.

2025-01-08 20:50 UTC, WackyWeaver commented on app/controllers/admin/graduationManagement.py
> +def gradsxls(filterType):
Maybe make this camelCase to match the rest of the functions.

2025-01-08 20:50 UTC, WackyWeaver commented on app/templates/admin/graduationManagement.html
> +      Bonner Cohorts
I believe this is the line, or it is near the line responsible for this issue. I thought it was a bit confusing that this made the "academic year" selection drop down default to "Bonner Cohort instead of the current year range. 
![image](https://github.com/user-attachments/assets/30acdbff-b87f-4e9f-abf1-d61292266417)

2025-01-08 20:50 UTC, WackyWeaver commented on app/static/js/graduationManagement.js
> +            msgFlash("Graduation status updated successfully!", "success");
This makes the flash messages a bit overwhelming if a user was attempting to graduate a lot of students at once. Also, when hitting "Select All" button, the message flashes for every user on the page individually. 
![image](https://github.com/user-attachments/assets/dafc59a3-8717-46b5-957c-882fe79a2d92)

2025-01-08 20:50 UTC, WackyWeaver commented on app/static/js/sidebar.js
> +  $('.alert').alert('close');// close excess flash messages from graduation managment
I was mentioning excess flash messages, and this might be the solution. I did not see it effect the flash notification I was getting.

2025-01-08 20:50 UTC, WackyWeaver commented on database/tmp-backups/2024-11-15-backup.sql
Why is this empty file here?

2025-01-28 22:41 UTC, thealphagurlux commented
The above naming conventions and issues with the multiple flash messages should be in working order. The sql file has also been removed.

2025-01-31 21:09 UTC, WackyWeaver reviewed
Here's the situation. You are so very close, but there are still a few things that need tweaked. The drop downs for academic year and student type need to respect each other when filtering the table. Also, I still would likely recommend renaming the "CheckIfNotGraduated" to something a bit more clear. I think you've made some good progress, and I like he filtering options. All together, keep it up!

2025-01-31 21:09 UTC, WackyWeaver commented on app/templates/admin/graduationManagement.html
> +        <a class="dropdown-item dropdown-item-new" data-filter = "bonner" data-cohort-year= "{{year}}" data-cohort-users = "{{bonnercohorts[year]}}" >{{year}}-{{year+1}}</a>
Since you are filtering for years with Bonner cohorts, I was running into issues if I wanted to look for a CCE minor student that wasn't a Bonner. The drop down created the same effect as that of the Bonner students filter.

2025-01-31 21:09 UTC, WackyWeaver commented on app/templates/admin/graduationManagement.html
> +      <a class="dropdown-item" data-filter="all" >All</a>
I'm a little curious of this feature. If I select a specific year with the other drop down, the "all" filter then would take priority. Would we want "all" to be separate from "all of a specific year"? 
Intuitively, I was assuming that the left drop down was filtering type of student and the center filter was for _**just**_ year.

2025-01-31 21:09 UTC, WackyWeaver commented on app/templates/admin/graduationManagement.html
> +      <td><input type="checkbox" class="graduated-checkbox" id = "gradCheck" data-username ="{{ user.username }}" {% if user.hasGraduated %}checked{% endif %}></td>
When I am flask running, I don't see the checkbox anymore. I was wondering if this idea was scratched.

2025-02-20 16:52 UTC, thealphagurlux commented on app/templates/admin/graduationManagement.html
> +      <td><input type="checkbox" class="graduated-checkbox" id = "gradCheck" data-username ="{{ user.username }}" {% if user.hasGraduated %}checked{% endif %}></td>
I don't think this is a flask problem, as I am able to see them. Double check as the check boxes are on the far left.

2025-03-20 19:22 UTC, thealphagurlux commented on app/templates/admin/graduationManagement.html
> +        <a class="dropdown-item dropdown-item-new" data-filter = "bonner" data-cohort-year= "{{year}}" data-cohort-users = "{{bonnercohorts[year]}}" >{{year}}-{{year+1}}</a>
The same user does appear in the table because they are both a Bonner and a CCE minor participant. In any case I think should be a different issue not related to this PR due to the lack of clarification from CELTS on what exactly they'd like, although I think that is a good feature that can be added.

2025-04-10 22:57 UTC, hoerstl requested changes
There are a couple of bugs that need fixing ~~~

2025-04-10 22:57 UTC, hoerstl commented on app/logic/graduationManagement.py
> +    elibibleUsers = (User.select(User.username, User.hasGraduated, User.classLevel, User.firstName, User.lastName, BonnerCohort.year)
Some might think that `eligibleUsers` is how it should be but I prefer `elibibleUsers`

2025-04-10 22:57 UTC, hoerstl commented on app/logic/graduationManagement.py
> +    gradStudent.hasGraduated = int(status)
Since hasGraduated is a boolean field, I think it would be more accurate to cast status to a boolean instead
`gradStudent.hasGraduated = bool(status)`

2025-04-10 22:57 UTC, hoerstl commented on app/templates/admin/graduationManagement.html
> +          </div>
This works but I feel it should be rewritten as a select attribute using options and values rather than bootstrap's dropdown classes. Feel free to disagree and dismiss this comment.

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +            data: {status: hasGraduated ? 1 : 0},
Let's remove the ternary operator and just return `hasGraduated` directly

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +                location.reload()
Let's not have this reload the whole page and instead just change the data or remove a row from the table instead

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +                location.reload()
There's no need to reload here. If there was an error then the graduation status wasn't updated and therefore there will be no corresponding change in the table that we'd need to reload for.

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +        location.reload()
I like setting this as part of the session for when people might come back to this page later but I don't think it should reload the page. We should find a way to give all seniors a row and conditionally hide the rows for those who have graduated.

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +    function filterTable(dataFilter, condition) {
Consider renaming the parameters to be more precise:
`function filterTable(dataField, expectedValue) {`

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +        $('#showGraduatedToggle').prop('checked', Number(showGraduatedToggleState));
### Big Bug

This breaks the `show graduated students` slider.

This line needs to be at the start of this function (and combined with the line that sets showGraduatedToggleState), otherwise the datatable filters out all of the graduates before the slider is checked.

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +        var showGraduatedToggleState = sessionStorage.getItem('showGraduatedToggleState') || false;
We only need this variable in one place. When we bring the line where we use this variable up to here we should just delete this initialization.

2025-04-10 22:57 UTC, hoerstl commented on app/static/js/graduationManagement.js
> +        handleMainFilterChange(mainFilterState, buttonText)
I feel as though these `mainFilterState` conditionals should be moved inside the `handleMainFilterChange` function

2025-04-10 22:57 UTC, hoerstl commented on app/templates/admin/graduationManagement.html
> +    </div>
I can't find what these empty spans do in the javascript anywhere so I think these should be deleted.

2025-04-10 22:57 UTC, hoerstl commented on app/templates/macros/graduationIconMacro.html
> +  <svg width="20px" height="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
If the macro takes in parameters, we should use them on this line to set the width and height.

2025-04-17 03:03 UTC, bledsoef commented on app/templates/macros/graduationIconMacro.html
> +  <svg width="20px" height="20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
You right you right.

2025-04-17 03:04 UTC, bledsoef commented on app/templates/admin/graduationManagement.html
> +    </div>
Copy and pasted from somewhere else in the app but you are right they are unnecessary.

2025-04-17 03:04 UTC, bledsoef commented on app/logic/graduationManagement.py
> +    elibibleUsers = (User.select(User.username, User.hasGraduated, User.classLevel, User.firstName, User.lastName, BonnerCohort.year)
I think elibible is quite apt

2025-04-17 03:06 UTC, bledsoef commented on app/logic/graduationManagement.py
> +    gradStudent.hasGraduated = int(status)
Intuitively this would make sense, however, Peewee isn't the smartest and for some reason it needs to be an int.

2025-04-17 03:08 UTC, bledsoef commented on app/templates/admin/graduationManagement.html
> +          </div>
I would generally agree that we should be consistent, but I think this looks better.

2025-04-17 03:11 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +            data: {status: hasGraduated ? 1 : 0},
Because we need it to be an int when saved to the db, if we do not do this it will be passed as the string 'true' and the int conversion won't work.

2025-04-17 03:12 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +                location.reload()
Let us discuss this in person my friend. I think there are many arguments to be made.

2025-04-17 03:12 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +                location.reload()
I think the reload is mainly for the flash error message.

2025-04-17 03:14 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +        var showGraduatedToggleState = sessionStorage.getItem('showGraduatedToggleState') || false;
For readability and consistency with the ones above I like it how it is.

2025-04-17 03:15 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +        $('#showGraduatedToggle').prop('checked', Number(showGraduatedToggleState));
My b my b.

2025-04-17 03:17 UTC, bledsoef commented on app/static/js/graduationManagement.js
> +        handleMainFilterChange(mainFilterState, buttonText)
I might disagree since the only other place that this is used we don't need the conditionals to determine what the buttonText should be.

2025-04-17 20:13 UTC, bledsoef commented on app/logic/graduationManagement.py
> +    gradStudent.hasGraduated = int(status)
Maybe add comment for clarity

2025-04-25 21:31 UTC, hoerstl approved these changes
Beautiful work!!

2025-04-25 21:32 UTC, merged