Event list rework issue135
BCStudentSoftwareDevTeam/celts pull request #150
Opened 2021-10-20 18:49 UTC by MayJue

This PR fixes issue #135. 

We remove the accordion on the list of events on the home page and replace them with tables(except for one. 
Then added a note for when there are no events. 
Also created test.

to test, go to the home page and select the different tabs.

2021-10-20 19:54 UTC, BrianRamsay requested changes

2021-10-20 19:54 UTC, BrianRamsay commented on app/logic/events.py
> +def getStudentLeadProgram(term):
This name should be StudentLed, not StudentLead

2021-10-20 19:54 UTC, BrianRamsay commented on app/logic/events.py
> +                                    Event.isTraining == False,
Is there a reason we are removing training events from here?

2021-10-20 19:54 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +                        <td> <a href="/{{program.id}}/{{event.id}}/edit_event" class="link-primary">{{event.name}}</a></td>
This isn't the right URL anymore. program is unnecessary when editing an event

2021-10-20 19:54 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +            <td> <a href="/{{event.program_id}}/{{event.id}}/edit_event" class="link-primary">{{event.name}}</a></td>
This url is wrong. Make sure when you're replacing a big block, that you identify changes that were made in that block

2021-10-20 19:54 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +            {% if (user.isCeltsAdmin) or (user.isCeltsStudentStaff) %}
use the `user.isAdmin` shortcut

2021-10-20 19:54 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +              {% if (event.event.startDate < currentTime.date()) or (event.event.timeStart < currentTime.time() and event.event.startDate == currentTime.date())%}
we'll use the `event.isPast` shortcut if it's available by the time this PR is ready. we'll see.

2021-10-20 19:54 UTC, BrianRamsay commented on tests/code/test_event_list.py
> +        studentProgramEvent = ProgramEvent.create(program = 2, event = studentLead)
if you want to save some space, you don't need to enter values for fields with defaults (like all the boolean ones that are 0)

2021-10-21 18:11 UTC, tylerpar99 commented
@BrianRamsay gets 6.5% credit for this PR per our contractual agreement.

2021-10-21 18:54 UTC, BrianRamsay requested changes
test_event_list.py has Windows line endings

2021-10-21 18:54 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +            <td> <a href="/{{event.id}}/edit_event" class="link-primary">{{event.name}}</a></td>
URL is not correct (see the removed code above)

2021-10-21 18:54 UTC, BrianRamsay commented on tests/code/test_event_list.py
> +        assert True not in [event.name == "Test Student Lead" for event in oneTimeEvents]
For these asserts, you have an event object you can use to directly check for inclusion (or not) in the event list.

2021-10-25 18:15 UTC, BrianRamsay requested changes
Go ahead and change the tab bar to tabs instead of pills (or whatever they are called)

2021-10-25 18:15 UTC, BrianRamsay commented on app/templates/events/event_list.html
> +                        {% if (user.isCeltsAdmin) or (user.isCeltsStudentStaff) %}
Here's another place you could use `user.isAdmin`

2021-10-25 19:05 UTC, BrianRamsay approved these changes
Good work!

2021-10-25 19:06 UTC, merged