Change Event Name
BCStudentSoftwareDevTeam/celts pull request #163
Opened 2021-10-29 15:26 UTC by sreynit02

Issue: Some events' names don't make sense and don't correspond to the program name that they are associated with.

Fix: Change events names so they relate to their program. Also changed location to real buildings. 

Test: Run tests and all of them should pass.

2021-10-29 17:12 UTC, bryantal commented on database/test_data.py
> +        "name": "Traing Event",
*Training

2021-10-29 17:19 UTC, bryantal commented on database/test_data.py
> +        "location": "Woodspen",
*Woods-Penniman

2021-10-29 17:19 UTC, bryantal commented on database/test_data.py
> +        "location": "Woodspen",
*Woods-Penniman

2021-10-29 17:20 UTC, bryantal reviewed
Just some spelling errors

2021-10-29 17:48 UTC, BrianRamsay requested changes
Thanks for making these changes! Alex found some spelling mistakes

2021-11-01 14:27 UTC, bryantal approved these changes

2021-11-02 13:48 UTC, BrianRamsay approved these changes

2021-11-02 13:48 UTC, merged