Front end for Issue 261 completed
BCStudentSoftwareDevTeam/celts pull request #287
Opened 2022-06-13 20:50 UTC by Boorclark

Created the front end for Issue #261. Mostaphe and I will work on the back end tomorrow. 

New Items:
- Date Created Header
- Date Entry Box

2022-06-15 14:17 UTC, BrianRamsay requested changes

2022-06-15 14:17 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +        print(datePassed)
Remove debug output

2022-06-15 14:17 UTC, BrianRamsay commented on app/models/backgroundCheck.py
> -
There should still be a new line between the fields and the key

2022-06-15 14:17 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +        bgDate: $("#" + checkType + "_date").val()
add a description like the other elements in the `data` dictionary

2022-06-15 14:17 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +        //location.reload()
Decide whether a reload is necessary. If so, uncomment this line, if not, remove it.

2022-06-15 14:17 UTC, BrianRamsay commented on app/templates/main/volunteerProfile.html
> +         <th scope="col"> Date Completed </th>
Remove whitespace around header

2022-06-15 18:25 UTC, BrianRamsay requested changes

2022-06-15 18:25 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +        bgDate: $("#" + checkType + "_date").val()  // Expected to be the type (ex. FBI) and  _date
The comment should be about the date itself, not what the line is doing. like, `// The date of the background check completion in YYYY/MM/DD format` (or whatever the format is)

2022-06-16 20:04 UTC, Boorclark reviewed
The comment has been fixed by Mostaphe.

2022-06-16 20:54 UTC, BrianRamsay approved these changes

2022-06-16 20:54 UTC, merged