Issue#268 admin check permessions
BCStudentSoftwareDevTeam/celts pull request #299
Opened 2022-06-16 14:55 UTC by martinj2-dot

Issue #268 

Created a test suite for getProgramManagerForEvent
Created a function getProgramManagerForEvent to allow Program managers to: return a peewee query that contains the database entry that matches a user to a program as managers.

Test suite location: /tests/code/test_volunteers.py
Function location: /app/logic/volunnteers.py
Added functionality location: app/controllers/admin/routes.py

Functionality allowed program managers to view and edit events they are the manager of.

Non-mangers can still view events in general.

2022-06-20 14:30 UTC, martinj2-dot commented
We think this issue is ready for review. We are still working on reducing the amount of queries in the test cases and making them self sufficient (Creating test data and deleting it once the tests finish.). We also would like to know where we could implement this function maybe that could be a separate issue?

2022-06-21 17:40 UTC, martinj2-dot commented
Used test data to create temporary rows in the database to test our function. Reduced the amount of queries from 12 to 8 and encapsulated it in a transaction to delete the data once test finishes. Added comments and cleaned up the code to improve readability.

2022-06-22 13:14 UTC, BrianRamsay requested changes

2022-06-22 13:14 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +    if not (g.current_user.isAdmin or getProgramManagerForEvent(g.current_user, programId = programid)):
What happens here if there is no program id from the route?

2022-06-22 13:14 UTC, BrianRamsay commented on app/logic/volunteers.py
> +    """
I like the description of the function

2022-06-22 13:14 UTC, BrianRamsay commented on app/logic/volunteers.py
> +def getProgramManagerForEvent(user, event= None, programId = None):
Two issues here:

1. The name is a bit off. It makes me think this is a function for figuring out who is the program manager for an event. If it returns a boolean, it should be something like `isProgramManagerForEvent`.
2. We already have a function to check if a user has permissions to mess with the program, `hasPrivilege` (also not a great name, admittedly). this one should just take a user and event, and call hasPrivilege to check the program.

2022-06-23 19:13 UTC, BrianRamsay requested changes

2022-06-23 19:13 UTC, BrianRamsay commented on app/logic/volunteers.py
> +def isProgramManagerForEvent(user, event= None):
Since you are not using program id here and event is required, you can remove the default value.

2022-06-23 19:13 UTC, BrianRamsay commented on app/logic/volunteers.py
> +        raise ValueError("Not enough parameters given to this function.")
Once you've removed the default value None, this bit isn't necessary anymore, as python will enforce passing the argument

2022-06-23 19:13 UTC, BrianRamsay commented on app/logic/volunteers.py
> +        programIdQuery = (ProgramEvent.get(ProgramEvent.event == event)).program
The Event class has a property `singleProgram`, which you can use to get the program id from an event or None if there are multiple programs or no programs

2022-06-23 19:13 UTC, BrianRamsay commented on app/logic/volunteers.py
> +        return False
Instead of saying essentially "if true equals true return true", just return the result. It's already True or False.

2022-06-23 19:13 UTC, BrianRamsay commented on tests/code/test_volunteers.py
> +        print(studentManager)
Remove the print statements

2022-06-27 18:28 UTC, BrianRamsay requested changes

2022-06-27 18:28 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +    if not (g.current_user.isAdmin):
The program manager should be able to create events for their programs, right? I thought this was already in there (and I see you are doing it down in edit event).

2022-06-27 18:28 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +    programManagerResult = isProgramManagerForEvent(g.current_user, event)
it's a good idea to name boolean variables so that they make expressions clearer. In this case, like `isProgramManager` or `canManageProgram`

2022-06-27 18:28 UTC, BrianRamsay commented on app/logic/volunteers.py
> +    programIdQuery = event.singleProgram
I would eliminate the variable here. It doesn't make it clearer (to me)

2022-06-28 14:00 UTC, martinj2-dot commented on app/controllers/admin/routes.py
> +    if not (g.current_user.isAdmin):
This is the only one we are confused about. Scott and I looked at this and don't know where to check if a user is a program manager for an event. Should it be located in validateNewEventData where all event data in the template is validated or should it check in attemptSaveEvent?

2022-06-30 14:33 UTC, BrianRamsay requested changes

2022-06-30 14:33 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +        allLogs = AdminLogs.select().order_by(AdminLogs.createdOn.desc())
This reverts the fix for the Admin Logs excess queries

2022-06-30 14:33 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +        allLogs = AdminLogs.select().order_by(AdminLogs.createdOn.desc())
Not sure how this snuck in there.

2022-06-30 20:35 UTC, BrianRamsay approved these changes

2022-06-30 20:35 UTC, merged