Resolve merge
BCStudentSoftwareDevTeam/celts pull request #306
Opened 2022-06-20 13:39 UTC by solijonovam

resolves the PR comments from issue 262 
also, resolves the merge conflict

2022-06-20 13:52 UTC, BrianRamsay requested changes

2022-06-20 13:52 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +  console.log(action)
Remove the debug output

2022-06-22 18:11 UTC, BrianRamsay requested changes
We should have an entry in AdminLog for this action. It can go in the controller.

2022-06-27 20:48 UTC, BrianRamsay submitted a review, later dismissed

2022-06-27 20:49 UTC, BrianRamsay commented
Looks good! But there's a conflict to resolve before I can merge it.

2022-06-28 13:45 UTC, BrianRamsay commented
Also, let's switch the positions on the page of the Service Learning Faculty table and the Course Proposal Management table.

2022-06-28 13:55 UTC, solijonovam commented
your comment seems to refer to another issue that is not related to the current PR.

2022-06-28 18:07 UTC, BrianRamsay commented
When you resolved the merge, you kept some of the wrong changes. You'll need to reset the branch back to the commit before the merge and try again (or create a new branch from that commit to preserve this one)

2022-06-30 14:04 UTC, BrianRamsay commented
Do you see how the tests fail? That's how I know you're not resolving the merge correctly. The `StudentManager` table you are trying to use no longer exists.

We can talk about it this afternoon if we need to.

2022-06-30 19:23 UTC, BrianRamsay approved these changes

2022-06-30 19:23 UTC, merged