Added datePassed attribute to setBackgroundCheck functions
BCStudentSoftwareDevTeam/celts pull request #307
Opened 2022-06-20 13:39 UTC by Boorclark

Fixed unit test to consider datePassed in test_volunteers.py

2022-06-22 18:24 UTC, BrianRamsay requested changes

2022-06-22 18:24 UTC, BrianRamsay commented on tests/code/test_volunteers.py
> +        updatebackground = setUserBackgroundCheck("khatts","FBI",True,"05-16-2003")
To avoid the peewee issues where dates are returned as strings, use datetime objects here instead of strings. add `from dateutil import parser` to your imports, and you can use `parser.parse()` to get date strings easily into dates.

2022-06-22 18:24 UTC, BrianRamsay commented on tests/code/test_volunteers.py
> +        assert updatedModel.datePassed.strftime("%m/%d/%Y") == "2004-15-06"
These dates wouldn't match even if the format was correct

2022-06-22 18:24 UTC, BrianRamsay commented on tests/code/test_volunteers.py
> +        assert updatedModel.datePassed.strftime("%m/%d/%Y") == "05-16-2003"
even if the dates are the same, you are comparing two different formats.

2022-06-23 14:19 UTC, mohamudm1 commented
Changes made:

1. Fixed the test suite 
2. Changed wherever there was a datePassed into dateCompleted to make it match the front end of the background check form.

2022-06-23 18:32 UTC, BrianRamsay approved these changes

2022-06-23 18:32 UTC, merged