Reduced Queries in Volunteer Profile by 25%
BCStudentSoftwareDevTeam/celts pull request #314
Opened 2022-06-22 20:00 UTC by Boorclark

Issue #245
Files Changed:
        modified:   app/logic/participants.py
        modified:   app/logic/utils.py
        modified:   app/models/term.py
        modified:   tests/code/test_utils.py

 - Simplified queries 
 - Updated test suite
 - Added method to term class

2022-06-23 20:42 UTC, BrianRamsay requested changes
Looking pretty good. We'll have to wait until the time selector changes are in to see if that gets rid of those changes in here.

2022-06-23 20:42 UTC, BrianRamsay commented on app/models/term.py
> +    def academicYearStartingTerm(self):
Give a brief description of what this function does. It's short, but it might not be clear at first glance

2022-06-24 17:03 UTC, Boorclark commented on app/models/term.py
> +    def academicYearStartingTerm(self):
The issue has been addressed. Resolving conversation.

2022-06-30 17:40 UTC, BrianRamsay commented
A lot of comments to resolve. Let's take a look

2022-06-30 19:45 UTC, BrianRamsay commented
This needs a merge from development and conflict resolution before review, @Boorclark , @Lyisus

2022-06-30 20:16 UTC, BrianRamsay requested changes
This table was renamed in development

2022-07-01 13:48 UTC, BrianRamsay approved these changes

2022-07-01 13:48 UTC, merged