Onetime events display138
BCStudentSoftwareDevTeam/celts pull request #330
Opened 2022-06-28 15:48 UTC by Boorclark

Fixes Issue #138 

Created a new query for the getnonProgramEvents function as well as changed this naming throughout the CELTS application (oneTimeEvent --> nonProgramEvent). Changed line 85 of the test suite to pass for now until Anderson changes this file. We also changed the Event List tab name to be "Other Events" and changed the create an event page to display "Create Non-Program Event". 

Files Changed:
- app/controllers/main/routes.py
- app/logic/events.py
- app/templates/admin/createSingleEvent.html
- app/templates/events/event_list.html
- tests/code/test_event_list.py

2022-06-30 14:44 UTC, BrianRamsay requested changes
so close! ;-)

2022-06-30 14:44 UTC, BrianRamsay commented on app/logic/events.py
> +def getnonProgramEvents(term):
That first 'N' should be capitalized.

2022-06-30 14:53 UTC, Boorclark commented on app/logic/events.py
> +def getnonProgramEvents(term):
We were so close this is so sad. Issue resolved

2022-07-01 14:12 UTC, BrianRamsay approved these changes

2022-07-01 14:13 UTC, merged