refactored ProgramManager permissions
BCStudentSoftwareDevTeam/celts pull request #345
Opened 2022-06-29 19:55 UTC by qasema

fixes issue #326 refactor PromgramManager permissions method and have hasPrivilege method as a method of the User object.

2022-06-30 14:01 UTC, BrianRamsay requested changes

2022-06-30 14:01 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +    user = User.get_by_id(g.current_user)
you already have a user in `g.current_user`. you don't need a database query to get the same user.

2022-06-30 14:01 UTC, BrianRamsay commented on app/models/user.py
> +        if ProgramManager.select().where(ProgramManager.user == self.username, ProgramManager.program == program).exists():
You can just use `self` instead of `self.username` (to make it a bit shorter), and then instead if `if <boolean> return True else return False`, you can just return the boolean you get from the `.exists()` query directly. `return ProgramManager.select...`

2022-06-30 14:01 UTC, BrianRamsay commented on tests/code/test_users.py
> +    assert not user.isProgramManagerFor(prg)
adding a test! nice.

2022-07-06 14:04 UTC, BrianRamsay commented
Don't forget this PR!

2022-07-06 18:18 UTC, qasema commented on app/controllers/admin/routes.py
> +    user = User.get_by_id(g.current_user)
I thought it is supposed to check different users not only the current user!

2022-07-06 18:54 UTC, qasema commented on app/controllers/admin/routes.py
> +    user = User.get_by_id(g.current_user)
I fixed this

2022-07-06 20:20 UTC, BrianRamsay requested changes

2022-07-06 20:20 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +    isProgramManager =   g.current_user.isProgramManagerFor(Program)
You're passing a class instead of a program object here.

2022-07-06 20:20 UTC, BrianRamsay commented on app/models/user.py
> +        if ProgramManager.select().where(ProgramManager.user == self.username, ProgramManager.program == program).exists():
not addressed yet.

2022-07-07 15:28 UTC, BrianRamsay approved these changes

2022-07-07 15:28 UTC, BrianRamsay commented
I've approved the PR but there are conflicts to resolve

2022-07-08 13:04 UTC, BrianRamsay submitted a review, later dismissed

2022-07-08 13:04 UTC, BrianRamsay commented
Ready to merge but there is a conflict

2022-07-08 13:29 UTC, qasema commented
I just resolved it

2022-07-08 13:49 UTC, BrianRamsay requested changes
There's an import of the old function that breaks in `app/logic/volunteers.py`

2022-07-12 13:26 UTC, BrianRamsay commented
Lots of windows line endings. It looks like development hasn't been merged in, so do that to see if it takes care of the issues.

2022-07-13 15:40 UTC, BrianRamsay reviewed
Merge conflict to resove

2022-07-13 18:48 UTC, BrianRamsay approved these changes

2022-07-13 18:48 UTC, merged