Added names to contributors file
BCStudentSoftwareDevTeam/celts pull request #373
Opened 2022-07-05 20:37 UTC by nartehi

Added names of everyone on the student developers team to the default.yml file.

2022-07-05 20:58 UTC, BrianRamsay requested changes

2022-07-05 20:58 UTC, BrianRamsay commented on app/config/default.yml
> +  - name: "Madina Solijonva"
Madina's name is spelled wrong

2022-07-05 20:59 UTC, BrianRamsay commented on app/config/default.yml
> +  - name: "Madina Solijonva"
Solijonova

2022-07-06 13:15 UTC, Boorclark commented on app/config/default.yml
> +  - name: "Madina Solijonva"
resolved

2022-07-06 14:06 UTC, BrianRamsay approved these changes

2022-07-06 14:07 UTC, merged