Review button model
BCStudentSoftwareDevTeam/celts pull request #419
Opened 2022-07-08 20:31 UTC by qasema

fixes issue #232 enable the review button to show the modal of the course proposal information and allow approve them
location: http://<IP>/manageServiceLearning

2022-07-11 19:28 UTC, BrianRamsay requested changes
There are multiple files with windows line endings

2022-07-12 13:59 UTC, BrianRamsay requested changes

2022-07-12 13:59 UTC, BrianRamsay commented on app/templates/serviceLearning/reviewproposal.html
> +  <div class="modal fade" tabindex="-1" id="myReview">
Looks like this file is old. Should it be removed?

2022-07-12 13:59 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +        courseID=request.form #has only the course id
don't name this variable courseID. It is form data.

2022-07-12 13:59 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +            flash("Course not approved", "warning")
This code is basically the same as the above, just without the call to `updateCourse`. Figure out how to repeat less code.

2022-07-12 13:59 UTC, BrianRamsay commented on app/static/js/courseManagement.js
> +  var courseID=$(el).attr('data-id');
if you are using data attributes, you can use the jquery method `.data('id')`

2022-07-12 13:59 UTC, BrianRamsay commented on app/static/js/courseManagement.js
> +  var courseID=$(el).attr('course-id');
I would use data attributes here. This works because you can set arbitrary attributes, but those should be in data attributes, really.

2022-07-12 13:59 UTC, BrianRamsay commented on app/templates/main/manageServiceLearningFaculty.html
> +<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
dataTables should be imported before the files that use it. Just in case.

2022-07-12 13:59 UTC, BrianRamsay commented on app/templates/main/manageServiceLearningFaculty.html
> +          {% for data in pendingCourses %}
`data` is too generic a name

2022-07-12 13:59 UTC, BrianRamsay commented on app/templates/main/reviewproposal.html
> +    <div id="myDIV1">Hello baby</div>
Not production text

2022-07-13 17:56 UTC, qasema commented on app/static/js/courseManagement.js
> +  var courseID=$(el).attr('data-id');
But the course Id is stored in an attribute called it "data-id"

2022-07-13 18:04 UTC, qasema commented on app/templates/main/reviewproposal.html
> +    <div id="myDIV1">Hello baby</div>
lol

2022-07-13 19:00 UTC, BrianRamsay requested changes

2022-07-13 19:00 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +    course_data=Course.get_by_id(courseID["course_id"])
This variable should just be `course` (in my opinion), since it is a course object. And then later you should use this variable instead of referencing the form data again.

2022-07-13 19:00 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +import re
You aren't using regular expressions, so you don't need this module.

2022-07-13 19:00 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +        course_data = request.form['courseID'] # if only course is reviewed pass the course ID
This isn't `course_data`, it's a `course_id`

2022-07-13 19:00 UTC, BrianRamsay commented on app/logic/courseManagement.py
> +    print("---------------------------------------")
debug output

2022-07-13 19:00 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +            course_data=course_upate['courseID']
`course_upate` is misspelled. Also, doesn't `course_upate['courseID']` break? what does `updateCourse` return?

You are mixing the data that is in `course_data` in the different cases, which can be very confusing later when you are using it.

2022-07-13 19:00 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +    course.execute() # Executes the query and approves course in the database
Since you should already have a course object from the above code, you can just use the `course.status = 2`, `course.save()` syntax for updating. Both work, but this is shorter

2022-07-13 19:00 UTC, BrianRamsay commented on app/static/js/courseManagement.js
> +  var courseID=$(el).attr('data-id');
That's what `.data('id')` looks for.

2022-07-13 19:00 UTC, BrianRamsay commented on app/static/js/courseManagement.js
> +  var courseID=$(el).attr('data-id');
`.attr()` works, but usually is used for manipulating standard attributes. you use `.data()` when you are using data attributes

2022-07-14 14:09 UTC, qasema commented
@BrianRamsay, you can take a look now!

2022-07-14 16:22 UTC, BrianRamsay requested changes

2022-07-14 16:22 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +import re
Doesn't look like you use the `count` module either

2022-07-14 16:22 UTC, BrianRamsay commented on app/controllers/serviceLearning/routes.py
> +from app.models import course
This is an unused import also. You might want to turn off whatever PyCharm setting is auto-adding imports

2022-07-14 16:22 UTC, BrianRamsay commented on app/logic/courseManagement.py
> +        coursebyid= Course.get_by_id(courseData['courseID'])
I would just call this one `course`, and then for confusion just remove the existing `course` variable from the `.update()`. It wasn't being used, anyway.

2022-07-14 16:22 UTC, BrianRamsay commented on app/templates/main/manageServiceLearningFaculty.html
> +<script src="/static/js/courseManagement.js"></script>
Let's put these indents back in.

2022-07-14 16:22 UTC, BrianRamsay commented on app/templates/main/manageServiceLearningFaculty.html
> +<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
put these indents back as well

2022-07-14 16:22 UTC, BrianRamsay commented on app/templates/serviceLearning/reviewproposal.html
> +  <div class="modal fade" tabindex="-1" id="myReview">
still relevant

2022-07-14 16:22 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +    course_data=Course.get_by_id(courseID["course_id"])
also still relevant

2022-07-14 17:33 UTC, qasema commented on app/controllers/main/routes.py
> +    course_data=Course.get_by_id(courseID["course_id"])
done

2022-07-14 17:34 UTC, qasema commented on app/templates/serviceLearning/reviewproposal.html
> +  <div class="modal fade" tabindex="-1" id="myReview">
Just deleted it

2022-07-14 19:55 UTC, BrianRamsay approved these changes
Woohoo!

2022-07-14 19:55 UTC, merged