Refactor Create Event Page #442
BCStudentSoftwareDevTeam/celts pull request #455
Opened 2022-07-13 18:42 UTC by Boorclark

Fixes Issue #442 

Changes Made:
 - Added conditional so users who are not CELTS Admins or Program managers cannot see the edit event tab or track volunteers
 - Added a View Event Tab
 - Got  the RSVP flash messages to display properly
 - Changed the way the RSVP buttons are accessed in the JS (no longer in a form)
 - Deleted createAllVolunteerEvent.html
 - Renamed createSingleEvent to createEvent across application
 - Cleaned up unneeded conditionals in the createEvent.html file
 - Added RSVP button in viewEvent.html

--------------------------------------------------------------------------------------------------------------------------------------------

Files Changed:
- app/controllers/admin/routes.py
- app/controllers/main/routes.py
- app/static/js/event_list.js
- app/templates/admin/createAllVolunteerEvent.html
- app/templates/admin/createEvent.html
- app/templates/eventView.html
- app/templates/events/trackVolunteers.html
- database/base_data.py

2022-07-13 19:13 UTC, BrianRamsay commented
A number of conflicts to resolve.

2022-07-13 21:25 UTC, BrianRamsay requested changes

2022-07-13 21:25 UTC, BrianRamsay commented on app/templates/eventView.html
> +{% endblock %}
Do you need bootstrap-select and jquery-ui for this page?

2022-07-13 21:25 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +    isProgramManager = hasPrivilege(g.current_user,program)
Merge in development. This will need to change.

2022-07-14 14:11 UTC, Boorclark commented on app/controllers/admin/routes.py
> +    isProgramManager = hasPrivilege(g.current_user,program)
resolved

2022-07-14 14:11 UTC, Boorclark commented on app/templates/eventView.html
> +{% endblock %}
resolved

2022-07-14 14:47 UTC, BrianRamsay commented
Merge conflict from a recent development change

2022-07-14 16:06 UTC, BrianRamsay approved these changes

2022-07-14 16:06 UTC, merged