Made separate function for getTemplates and updated getPrograms.
BCStudentSoftwareDevTeam/celts pull request #459
Opened 2022-07-13 20:42 UTC by bledsoef

Adjusted the templateSelect controller method to utilize getPrograms more and made a function getTemplates toi remove any unnecessary conditionals.

Fixes issue #458

2022-07-13 21:06 UTC, BrianRamsay requested changes
We need to add tests for the new functionality in `getPrograms` and for `getTemplates`. And while we're at it, we should rename them to `getAllowedPrograms` and `getAllowedTemplates` (or better names if you think of better ones).

2022-07-14 14:50 UTC, BrianRamsay requested changes
Get in the habit of testing your pages after you make changes. This breaks just clicking on Create Event

2022-07-14 14:50 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +        visibleTemplates = getTemplates(g.current_user)
This no longer works.

2022-07-14 15:07 UTC, Boorclark commented on app/controllers/admin/routes.py
> +        visibleTemplates = getTemplates(g.current_user)
resolved

2022-07-14 15:13 UTC, BrianRamsay approved these changes

2022-07-14 15:13 UTC, merged