Redesign event view page
BCStudentSoftwareDevTeam/celts pull request #590
Opened 2022-07-25 14:51 UTC by mohamudm1

Changes made:
Redesigned the view event page complete. You can see what it looked like before and how it looks not below
![Even View Page Window ](https://user-images.githubusercontent.com/97688286/180806205-7fb447bf-50f8-4ee5-94a1-d21e84b1dff4.PNG)
![After](https://user-images.githubusercontent.com/97688286/180806230-9c2d4974-eebd-4458-b937-7e155604ea62.PNG)

2022-07-25 18:09 UTC, zachneill requested changes, later dismissed

2022-07-25 18:09 UTC, zachneill commented on app/templates/eventView.html
> +                    <div style="padding-right:150px;"class="col-md-6">
The padding-right here gets a bit noticeable on smaller screens and especially mobile. Taking out the padding looked okay. If you still want padding, I'd suggest using rem or similar, not pixels.

2022-07-25 18:09 UTC, zachneill commented on app/static/css/base.css
> +.size{
The class name "size" is pretty unindicative. A slightly more obvious name would be helpful

2022-07-25 18:09 UTC, zachneill commented on app/templates/eventView.html
> +                <div class=" col-md-6">
If you made it this far, might as well remove the added spaces in front of your col-md-6 's. I'm assuming you removed a class in front of it...

2022-07-25 19:16 UTC, BrianRamsay commented
Let's try putting that first descriptive sentence above the Description and Facilitators headers. I also think the font-size class can go. The smaller text is fine, since that's the default text size we use in the rest of the application

2022-07-27 14:54 UTC, BrianRamsay requested changes

2022-07-27 14:54 UTC, BrianRamsay commented on app/templates/eventView.html
> +                              <div><h3><br>Program Manager</h3></div>
No reason for a div around the header that I can see.

2022-07-27 14:54 UTC, BrianRamsay commented on app/templates/eventView.html
> +                            <br />
Put all of these in <p> tags, instead of using breaks

2022-07-27 14:54 UTC, BrianRamsay commented on app/templates/eventView.html
> +            <div style="padding-top:100px;"class="text-center">
We want to avoid style tags, and avoid defining things with pixels

2022-07-28 13:54 UTC, BrianRamsay approved these changes

2022-07-28 13:56 UTC, merged