Fixed the phone number input box in "My Profile"
BCStudentSoftwareDevTeam/celts pull request #620
Opened 2022-07-27 17:15 UTC by Boorclark

Fixes Issue #615 

Changes Made:
 - Updated UI to match the SLC proposal
 - Fixed the backend for the Edit/Save

2022-07-28 13:50 UTC, BrianRamsay requested changes
Make sure you are testing your code thoroughly. The `invalid` class isn't doing anything on this page.

2022-07-28 13:50 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +        $(this).html('Edit');
Phone number handling is now duplicated. Let's make a function that these two places can share.

2022-08-01 19:58 UTC, BrianRamsay requested changes

2022-08-01 19:58 UTC, BrianRamsay commented on app/static/js/base.js
> +        $('#phoneInput').inputmask('(999)-999-9999');
You don't need to do the inputmask step more than once when the page loads

2022-08-01 19:58 UTC, BrianRamsay commented on app/static/js/base.js
> +        if (!(isvalid || isempty)) {
Maybe we should have a comment here clarifying that this expression allows the phone input to be empty.

2022-08-01 19:58 UTC, BrianRamsay commented on app/static/js/base.js
> +          msgFlash("Invalid Phone number", "danger")
This could just go up with the other things that happen when it is invalid

2022-08-01 19:58 UTC, BrianRamsay commented on app/static/js/base.js
> +        if (isvalid == true){
We want to be able to save an empty phone number, so we can just get rid of this isvalid check.

2022-08-02 15:39 UTC, BrianRamsay approved these changes
Nice!

2022-08-02 15:39 UTC, merged

2022-08-02 15:42 UTC, zachneill commented on app/templates/main/volunteerProfile.html
> +          <input type="text" style="border: none" size="12" class="form-control-sm bfh-phone"  id="phoneInput" value="{{volunteer.phoneNumber}}"/>
There's a bootstrap equivalent for "border:none"

2022-08-02 15:42 UTC, zachneill commented on app/static/js/slcNewProposal.js
> +            var phoneInput = "#inputPhoneNumber-" + username
It's 2022 stop using var 

Either use const or let, or clock out and go back to gardening and watching The Price is Right.

2022-08-02 15:42 UTC, zachneill commented on app/static/js/base.js
> +            phoneInput.focus()
Missing semicolons in this file. Also stop using var, grandma.

2022-08-02 15:42 UTC, zachneill commented on app/static/js/base.js
> +            phoneInput.focus()
Missing semicolons in this file. Also stop using var, grandma.

2022-08-02 15:44 UTC, zachneill commented
Commented after this was merged smh