Fixed conditionals and column name
BCStudentSoftwareDevTeam/celts pull request #621
Opened 2022-07-27 20:45 UTC by Boorclark

Fixes Issue #565 

Changes Made:
 - Changes JS conditionals 
 - Completed --> Passed

2022-07-28 13:39 UTC, BrianRamsay requested changes
I think a better fix is to have 3 options in the select box, because we need to be able to tell a difference between No and never updated. Whether they are choosing yes or no, we still need a date.

2022-08-01 17:00 UTC, BrianRamsay requested changes

2022-08-01 17:00 UTC, BrianRamsay commented on app/logic/volunteers.py
> +            createLog(f"Marked {user.firstName} {user.lastName}'s background check for {bgType} as incompleted.")
They are marking them as "Passed" and "Not Passed" now, not complete or incomplete

2022-08-01 17:00 UTC, BrianRamsay commented on app/static/js/volunteerProfile.js
> +    if (checkPassed && bgDate == '' ) {
Does this work with checkPassed = 0?

2022-08-01 18:00 UTC, bledsoef commented on app/logic/volunteers.py
> +            createLog(f"Marked {user.firstName} {user.lastName}'s background check for {bgType} as incompleted.")
resolved

2022-08-01 18:00 UTC, bledsoef commented on app/static/js/volunteerProfile.js
> +    if (checkPassed && bgDate == '' ) {
resolved

2022-08-01 19:59 UTC, BrianRamsay approved these changes

2022-08-01 19:59 UTC, merged