Issue#383 allow multiple attachments
BCStudentSoftwareDevTeam/celts pull request #640
Opened 2022-08-03 18:00 UTC by martinj2-dot

Fixed an issue with creating events. Issue 383

2022-08-03 18:01 UTC, BrianRamsay approved these changes, later dismissed

2022-08-04 17:28 UTC, BrianRamsay requested changes

2022-08-04 17:28 UTC, BrianRamsay commented on app/logic/events.py
> +            events = saveEventToDb(newEventData)
Let's reorganize this so that the attachmentFiles check just decides whether we do the addfile loop. Because everything else is the same

2022-08-04 17:28 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +        fileDoesNotExist = attachmentFiles[0].content_type == "application/octet-stream"
Could we just make attachmentFiles = None here if there are no files? We wouldn't need a conditional later

2022-08-04 20:55 UTC, Andersonstettner approved these changes, later dismissed

2022-08-05 02:32 UTC, BrianRamsay requested changes

2022-08-05 02:32 UTC, BrianRamsay commented on app/controllers/admin/routes.py
> +                attachmentFiles = None
Let's just do this up where I made the comment, and avoid having to do a conditional here at all

2022-08-05 02:32 UTC, BrianRamsay commented on app/logic/events.py
> +        if  attachmentFiles != None:
Did `if attachmentFiles` not work? Seems like it would, and that is preferred over a double negative

2022-08-05 15:20 UTC, BrianRamsay approved these changes

2022-08-05 15:20 UTC, merged