Adding volunteer hours issue 622
BCStudentSoftwareDevTeam/celts pull request #641
Opened 2022-08-03 19:41 UTC by bledsoef

Fixes issue #622 

Changes Made:
- Made the hours auto save when a new user is submitted
- If the event has passed, user hours default to event length, otherwise, they default to none
- Added tests for new function
- Made the track volunteers page show an accumulation between RSVP'd users and manually added users

2022-08-03 20:10 UTC, BrianRamsay requested changes

2022-08-03 20:10 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +    eventVolunteerData = (eventRsvpData + list(set(eventParticipantData) - set(eventRsvpData)))
if you want to get uniques, you can do it shorter by casting to a set and then back to a list: `eventVolunteerData = list(set(eventParticipantData + eventRsvpData))`

2022-08-03 20:10 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +    eventVolunteerData = (eventRsvpData + list(set(eventParticipantData) - set(eventRsvpData)))
On second thought I'm not sure how there would be duplicates, if one set is EventRsvp objects and the other set is EventParticipant

2022-08-03 20:10 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +        userAdded = EventRsvp.get_or_none(user = user, event = eventId)
I think I would call this `rsvpExists`, since it's more a question of what the state currently is, than what action have we performed.

2022-08-03 20:10 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +                    EventParticipant.create(user = user, event = eventId, hoursEarned = eventHours)
We are we only creating this record if they haven't rsvp'd? This is confusing to me.

2022-08-03 20:10 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +                    EventParticipant.create(user = user, event = eventId)
If the event is in the future this should be an rsvp, not a participant

2022-08-03 20:10 UTC, BrianRamsay commented on app/logic/participants.py
> +        program = Program.select(Program).join(ProgramEvent).where(ProgramEvent.event == event).get()
You don't need to get the program - that's what `rsvpEvent.singleProgram` already is

2022-08-03 20:10 UTC, BrianRamsay commented on tests/code/test_participants.py
> +from dateutil import parser
Put the library imports together (as opposed to our app). An organizational thing

2022-08-12 16:58 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Adding Volunteer with their hours #622](https://trello.com/c/g3u99aXv/404-adding-volunteer-with-their-hours-622)

2022-08-17 16:37 UTC, BrianRamsay approved these changes

2022-08-17 16:37 UTC, merged