Background Check Rework & New Modal
BCStudentSoftwareDevTeam/celts pull request #673
Opened 2022-08-05 18:16 UTC by Boorclark

### **Fixes Issues #661 & #662**

### Changes Made
- Renamed volunteerProfile -> userProfile
- Renamed setUserBackgroundCheck to addUserBackgroundCheck
- Renamed the Statuses of the background checks
- Changes background check functionality (now they are just entry points)
- Created a history modal for each background check type
- Updated test to account for new status and function
--------------------------------------------------------------------------------------------------------------------------------------------
### How To Test
> **For testing UI**
1. In your terminal, enter **database/reset_database.sh  test**
2. In your terminal, enter **flask run**
3. Navigate to the **Student Search** page
4. Search any user (Example: neillz)
5. Scroll down to background checks and enter different dates and statuses for each
6. Click on the **History** hyperlink
7. Behold glory

> **For testing unit test**
1. In your terminal, enter **tests/monitor.sh**
2. The test that relates to this issue is located in **test_volunteers.py**

2022-08-10 14:54 UTC, BrianRamsay requested changes

2022-08-10 14:54 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +        print(checkPassed)
debug output

2022-08-10 14:54 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +            allEntries[type.id] = [[allBackgroundCheck.backgroundCheckStatus, allBackgroundCheck.dateCompleted.strftime("%m/%d/%Y")] for allBackgroundCheck in allBackgroundChecks]
This should be a function

2022-08-10 14:54 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +            allEntries[type.id] = [[allBackgroundCheck.backgroundCheckStatus, allBackgroundCheck.dateCompleted.strftime("%m/%d/%Y")] for allBackgroundCheck in allBackgroundChecks]
And the separate query for BackgroundCheckType seems unnecessary since you have to do a query to get a bunch of background checks entries anyway

2022-08-10 14:54 UTC, BrianRamsay commented on app/static/js/userProfile.js
> +    console.log(checkPassed)
debug output

2022-08-12 16:58 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Background check renaming and rework dropdown options #661](https://trello.com/c/R0qN4zD8/460-background-check-renaming-and-rework-dropdown-options-661)

2022-08-12 17:00 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Background check history #662](https://trello.com/c/eaQWyWnZ/461-add-background-check-history-662)

2022-08-16 20:48 UTC, BrianRamsay requested changes
The visual display is a bit weird. The select box should be the same size as the date selector and the button

2022-08-16 20:48 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +                        Status: {{allEntries[bgType.id][0][0]}} as of {{allEntries[bgType.id][0][1]}} &nbsp&nbsp<a id="-{{bgType.id}}" type='button' onclick="showHistory(this)" href="#">History</a>
This doesn't work

2022-08-16 20:48 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +                         {% endif %}
This display doesn't work. Also, use a class to add the bold text to the first item so you don't have to have a conditional in jinja

2022-08-17 16:07 UTC, BrianRamsay approved these changes

2022-08-17 16:07 UTC, merged