When the User clicks renew they are now taken to the edit page for that newly renewed proposal
BCStudentSoftwareDevTeam/celts pull request #682
Opened 2022-08-11 16:12 UTC by Andersonstettner

2022-08-11 16:12 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Renew button should result in the Edit page, not management #648](https://trello.com/c/ZDUBmsmg/446-renew-button-should-result-in-the-edit-page-not-management-648)

2022-08-12 18:32 UTC, BrianRamsay requested changes

2022-08-12 18:32 UTC, BrianRamsay commented on app/static/js/slcManagement.js
> +        location = '/serviceLearning/editProposal/' +courseID;
You are editing the wrong course. This is the edit page for the old course, not the new one.

2022-08-16 20:50 UTC, BrianRamsay requested changes

2022-08-16 20:50 UTC, BrianRamsay commented on app/static/js/slcManagement.js
> +        location = '/serviceLearning/editProposal/' + s;
`s` isn't a descriptive enough variable name.

2022-08-17 16:09 UTC, BrianRamsay approved these changes

2022-08-17 16:09 UTC, merged