Added the users participation history to volunteerProfile
BCStudentSoftwareDevTeam/celts pull request #683
Opened 2022-08-12 13:30 UTC by Andersonstettner

2022-08-12 13:31 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Volunteer's history #664](https://trello.com/c/G8D7OQYt/463-add-volunteers-history-664)

2022-08-12 18:31 UTC, BrianRamsay requested changes

2022-08-12 18:31 UTC, BrianRamsay commented on app/logic/events.py
> +                                (Program.isBonnerScholars == False)))
We should put parentheses around the `Program.` pair so we are explicit about the order.

2022-08-12 18:31 UTC, BrianRamsay commented on app/controllers/events/routes.py
> -    return render_template('/events/showUpcomingEvents.html',
You should get rid of the unused template as well

2022-08-12 18:31 UTC, BrianRamsay commented on tests/code/test_events.py
> +
I would check an event that SHOULDN'T be returned as well, to make sure your query isn't just getting a bunch of extra events.

2022-08-16 21:00 UTC, BrianRamsay requested changes

2022-08-16 21:00 UTC, BrianRamsay commented on app/models/event.py
> +        if self._spCache is "Empty":
Use `==` instead of `is`

2022-08-16 21:00 UTC, BrianRamsay commented on app/models/event.py
> +        if self._spCache is "Empty":
This warning shows up in the `flask run` output.

2022-08-17 16:08 UTC, BrianRamsay approved these changes

2022-08-17 16:09 UTC, merged