Profile refactor
BCStudentSoftwareDevTeam/celts pull request #684
Opened 2022-08-12 18:50 UTC by Andersonstettner

2022-08-12 18:51 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Volunteer Profile page view #663](https://trello.com/c/j4wn5uK0/462-refactor-volunteer-profile-page-view-663)

2022-08-18 17:35 UTC, BrianRamsay requested changes

2022-08-18 17:35 UTC, BrianRamsay commented on app/__init__.py
> +    # gets the current accoridon and assigns it to g.visibleAccordion
This comment isn't accurate.

2022-08-18 17:35 UTC, BrianRamsay commented on app/static/js/userProfile.js
> +          var date = new Date(`${data.bgDate}`).toLocaleDateString()
There's no reason to put your string variable into a string to pass it to `Date()`. Just use the variable.

2022-08-18 17:35 UTC, BrianRamsay commented on app/templates/admin/userManagement.html
> +      {% set show = "show" if visibleAccordion == "program" else "" %}
Go ahead and add this to the other accordion panes as well.

2022-08-18 17:35 UTC, BrianRamsay commented on app/templates/admin/userManagement.html
>        {% endif %}
Let's make this check match the other one in terms of variable names and style

2022-08-18 17:35 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +                         {% if allBackgroundHistory[bgType.id][0] %}
This conditional is unnecessary. the for loop will either happen or not anyway, which is what we want.

2022-08-18 20:59 UTC, BrianRamsay requested changes

2022-08-18 20:59 UTC, BrianRamsay commented on app/static/js/userManagement.js
> +      location.replace(origin + "?accordion=term")
We should make this a function so we can just call `reloadWithAccordion("term")`

2022-08-19 15:22 UTC, BrianRamsay approved these changes

2022-08-19 15:22 UTC, merged