fix accodion conditional
BCStudentSoftwareDevTeam/celts pull request #707
Opened 2022-08-25 20:08 UTC by qasema

fixes issue #697 open only relevant accordions to the current user in the profile page

2022-08-25 20:16 UTC, Andersonstettner requested changes

2022-08-25 20:16 UTC, Andersonstettner commented on app/templates/main/userProfile.html
> +      <!-- {% set focus = "open" if not visibleAccordion or visibleAccordion == "upcoming" else "collapsed" %} -->
Without this piece the Upcoming Events accordion is focused despite it not being the open accordion. Make sure the accordion that is open is always the one that is focused. 
How the page currently looks on page load:
![image](https://user-images.githubusercontent.com/26262045/186759952-41ace136-2865-443e-bdcd-4b2fc6b33373.png)

How the page should look on page load:
![image](https://user-images.githubusercontent.com/26262045/186760042-ad506514-aece-4e12-b76a-f0994aeb2d9f.png)

2022-09-01 16:25 UTC, Andersonstettner requested changes
Close but still not entirely there. Now, after the page is reloaded following the user selecting an interest, both the upcoming accordion and the programs accordion are open. 
![image](https://user-images.githubusercontent.com/26262045/187964818-44ca8c1e-6986-4460-b504-835ed9c4d126.png)

2022-09-02 20:14 UTC, Karina-Agliullova commented
It works. Good job!

2022-09-02 20:14 UTC, Karina-Agliullova approved these changes

2022-09-02 20:17 UTC, Andersonstettner approved these changes

2022-09-02 20:17 UTC, merged