Add new background check type, disable save after press, and allow deletion of BG check
BCStudentSoftwareDevTeam/celts pull request #751
Opened 2022-09-15 15:37 UTC by Andersonstettner

Issue: CELTS asked for a new background check type to be added (Student Life BG check). They also had times where the double clicked the save button so they wished for it to be disabled after they clicked it and wanted to be able to delete background checks. 

Did: Added the new background check time called Berea Student Life (BSL). I also disabled the save button until after the ajax succeed in saving the BG check and then it would be reenabled.

2022-09-15 15:37 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a new Background check category: Student Life. Also give admin the ability to delete a BG check and disable the save button after it has been pressed #749](https://trello.com/c/4U3spXI4/542-add-a-new-background-check-category-student-life-also-give-admin-the-ability-to-delete-a-bg-check-and-disable-the-save-button-af)

2022-09-21 13:19 UTC, BrianRamsay requested changes

2022-09-21 13:19 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +        BackgroundCheck.delete().where(BackgroundCheck.id == bgId).execute()
`bgId` isn't an id, it's a `BackgroundCheck` object

2022-09-21 13:19 UTC, BrianRamsay commented on app/static/js/userProfile.js
> +      return false
In each of these we are selecting the same element multiple times. Save it in a variable at the top so you only have to get it once.

2022-09-21 13:19 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +            <table class="table" id="bgHistoryTable" name="bgHistoryTable">
The `name` attribute is meaningless for non-form elements, as far as I know.

2022-09-21 14:09 UTC, BrianRamsay approved these changes

2022-09-21 14:09 UTC, merged