Bonner Cohort Management
BCStudentSoftwareDevTeam/celts pull request #765
Opened 2022-09-21 18:17 UTC by BrianRamsay

I have added basic data structures and an admin management page for Bonner cohorts.

CELTS admins should be able to:
- view all bonner students in a list within their cohorts
- add students to different Bonner years
- download an excel document with all of the bonner students.
- view a basic list of bonner events for the term with the # of rsvps and participants

Resolves issues #731 and #734

2022-09-21 19:43 UTC, sreynit02 reviewed
Some recommendation for the UI:
-When displaying the cohorts (years &all bonners in each year), we think it might look better if make each year and the corresponding bonners in different column. That way there is less white space to the right. Also, we actually display all the bonners in each cohort, the accordion would not be too long vertically if we display each year into columns. 
-We also think that when displaying all the bonner cohorts, the font of the year should be bigger than the student names.

2022-09-22 16:39 UTC, Andersonstettner commented
Not necessarily related to this PR just something I noticed: The description for Bonners on the Service Transcript is the Habitat for Humanity description.

2022-09-22 16:41 UTC, Andersonstettner commented
Another thing for future consideration: It has been mentioned briefly in the past that we will probably need different behaviors for when a student leaves Bonners because they don't want to do it anymore vs. when they are asked/forced to leave.

2022-09-22 17:07 UTC, Andersonstettner requested changes

2022-09-22 17:07 UTC, AndersonStettner commented on app/templates/admin/bonnerManagement.html
> +    {% set show = "show" if visibleAccordion == "requirements" else "" %}
Your accordion focus/opening is off:
![image](https://user-images.githubusercontent.com/26262045/191799144-28d880fd-8c09-4bab-928e-0855d1b58478.png)

2022-09-22 17:07 UTC, AndersonStettner commented on app/templates/admin/bonnerManagement.html
> +                  <h5>You have no Bonner events.</h5>
Personally, I don't think we should use personal wording here. The page is, in my head, a general info page that the admin will use for Bonner so, it would be better to say something like "There are no Bonner events."

2022-09-22 17:07 UTC, Andersonstettner commented on app/models/bonnerYear.py
> +class BonnerYear(baseModel):
Personally, I do not like the name BonnerYear and I think it is a bit misleading. Just by going off of the name it seems like it is just keeping track of cohort years ( my first impression when I saw it was that it was keeping track of which years were which cohort) but it is actually all of the Bonners with the cohort year they are in. I think we might want to rename it to better match what it actually is.

2022-09-22 20:16 UTC, BrianRamsay commented
> Some recommendation for the UI: -When displaying the cohorts (years &all bonners in each year), we think it might look better if make each year and the corresponding bonners in different column. That way there is less white space to the right. Also, we actually display all the bonners in each cohort, the accordion would not be too long vertically if we display each year into columns. 

Do you think the contents of the accordion should scroll right and left to see all of the columns or reflow depending on the width of the page? Or, do we even need 'All', since they have the option to download the whole list

2022-09-22 20:30 UTC, Andersonstettner commented
Lets add a few students as Bonners to base data.

2022-09-23 19:31 UTC, sreynit02 commented
> 

I think scrolling left-right would be worse than up-down.  I think we don't need 'All' at all because we already displayed them under the search box for every year. If we got rid of "All",  we should add the volunteer profile link when we display their names for each year. 

A recommendation to remove the white space to the right of the Cohort Management accordion would be to center the content and make the year tabs' length the same length as the space bar column.

2022-09-23 19:32 UTC, sreynit02 commented
> > Some recommendation for the UI: -When displaying the cohorts (years &all bonners in each year), we think it might look better if make each year and the corresponding bonners in different column. That way there is less white space to the right. Also, we actually display all the bonners in each cohort, the accordion would not be too long vertically if we display each year into columns.
> 
> @sreynit02 Do you think the contents of the accordion should scroll right and left to see all of the columns or reflow depending on the width of the page? Or, do we even need 'All', since they have the option to download the whole list?

I think scrolling left-right would be worse than up-down. I think we don't need 'All' at all because we already displayed them under the search box for every year. If we got rid of "All", we should add the volunteer profile link when we display their names for each year.

A recommendation to remove the white space to the right of the Cohort Management accordion would be to center the content and make the year tabs' length the same length as the space bar column.

2022-09-26 15:59 UTC, BrianRamsay commented
I removed 'All' and centered the columns. Do we like it centered or left-justified better?

2022-09-26 16:29 UTC, sreynit02 commented
> I removed 'All' and centered the columns. Do we like it centered or left-justified better?

Centered please :)

2022-09-26 17:19 UTC, Andersonstettner approved these changes
We probably want to add one or two people as Bonners in base data and fix the tests if they break due to those additions. Aside from that, I think everything is looking good.

2022-09-28 14:04 UTC, merged