Time check
BCStudentSoftwareDevTeam/celts pull request #803
Opened 2022-11-29 21:48 UTC by thawpt

Did:
- Check to make sure start time is not after end time
- Made sure start time is not the same as the end time
- Added a clearer error message
Test:
- Create an event- make it recurring, make end time a time before the start time
- Once you try to create event, the error message "Event end time must be after start time." should pop up 
- Create an event- make it recurring, make end time the same as start time
- Once you try to create event, the error message "Event end time must be after start time." should pop up

2022-11-30 20:25 UTC, Andersonstettner requested changes
Make sure that if the event is not created due to one of the blockers (ie: the start and end time are the same) when the page is reloaded to show the error message the event is still marked as a recurring event.

2022-12-01 19:48 UTC, Andersonstettner commented
Almost, after reload the recurring switch is still checked but the "End Date" box does not appear.
![image](https://user-images.githubusercontent.com/26262045/205145826-733a099f-dcbc-464d-ad64-b267dffb41d0.png)

2022-12-05 15:09 UTC, AndersonStettner requested changes

2022-12-05 15:09 UTC, AndersonStettner commented on app/templates/admin/createEvent.html
> +            {%if eventData.isRecurring == True and isNewEvent%}
Set a variable to that will add or remove d-none depending on the condition so we don't have to repeat everything kind of like how we show and focus accordions.

2022-12-05 20:46 UTC, sreynit02 commented on app/templates/admin/createEvent.html
> +            {%if eventData.isRecurring == True and isNewEvent%}
fixed!

2022-12-13 14:28 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [End Time is not checked when creating recurring events #768](https://trello.com/c/0s7oG47P/586-end-time-is-not-checked-when-creating-recurring-events-768)

2023-01-13 20:56 UTC, Andersonstettner requested changes

2023-01-13 20:56 UTC, Andersonstettner commented on app/static/js/createEvents.js
> +      debugger;
Remove debug code

2023-01-13 21:00 UTC, qasema commented on app/static/js/createEvents.js
> +      debugger;
@Andersonstettner removed

2023-01-13 21:18 UTC, Andersonstettner requested changes

2023-01-13 21:18 UTC, Andersonstettner commented on app/static/js/createEvents.js
> +  }
Remove this check, it does not have any actual use and it breaks the code.

2023-01-13 21:31 UTC, Andersonstettner commented on app/static/js/createEvents.js
> +  }
Keep check but change it to check if the start and end dates are different instead

2023-01-23 20:17 UTC, Karina-Agliullova commented on app/templates/admin/createEvent.html
> +            {%if eventData.isRecurring == True and isNewEvent%}
Add space after and before the "%" sign when using jinja in all jinja code

2023-01-23 20:19 UTC, Karina-Agliullova reviewed
Everything is fine. It just looks messy when spaces are not used in jinja code. so please include them. Other than that, good job!

2023-01-23 20:32 UTC, Karina-Agliullova commented
![Screenshot (1286)_LI](https://user-images.githubusercontent.com/68787691/214143023-043593e3-3550-40b8-941b-5dc7d3c25b57.jpg)
![Screenshot (1287)_LI](https://user-images.githubusercontent.com/68787691/214143044-6e0cf0ef-7274-497a-bfce-26ace369c0c1.jpg)
When creating an event and setting it as recurring, after clicking save and saving it successfully, the end date option disappears. Also, if you check the saved recurring event on the events list page and try to edit one of the upcoming events, the end date option is also missing on the edit event page. Investigate why it occurs and fix the issue

2023-01-23 21:00 UTC, Karina-Agliullova approved these changes
Good work!

2023-01-24 13:36 UTC, Andersonstettner approved these changes
Looks good, good job!

2023-01-24 13:36 UTC, merged