Changed past event messaging and renamed sendRecommendation function everywhere.
BCStudentSoftwareDevTeam/celts pull request #839
Opened 2023-02-09 17:50 UTC by Andersonstettner

2023-02-09 17:52 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Issues from Mega-branch #837](https://trello.com/c/ZGVSHUPX/598-issues-from-mega-branch-837)

2023-02-14 14:39 UTC, bledsoef requested changes

2023-02-14 14:39 UTC, bledsoef commented on app/templates/admin/createEvent.html
> +      <h3>This is a past event!</h3>
No, bad. This is also not a change that is reflected on trackVolunteers or viewEvent.

2023-02-20 20:37 UTC, qasema commented
On the landing page, when clicking on "learn more" of any card. It should take you to the corresponding celts website page for that program. Now, it just redirects to the same landing page.

2023-02-20 20:42 UTC, qasema commented
fix "Bonner Scholar" to "Bonner Scholars"

2023-02-21 20:39 UTC, qasema commented
still fix "Bonner Scholar" to "Bonner Scholars" Scholar should be plural

2023-02-22 21:11 UTC, qasema submitted a review, later dismissed

2023-02-28 15:42 UTC, BrianRamsay approved these changes

2023-02-28 15:43 UTC, merged