Add ability to limit event RSVP and add a RSVP waitlist
BCStudentSoftwareDevTeam/celts pull request #849
Opened 2023-03-08 17:04 UTC by Andersonstettner

2023-03-08 17:04 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to limit the number of volunteers that can RSVP to an event. #748](https://trello.com/c/HsFbG9aG/541-add-the-ability-to-limit-the-number-of-volunteers-that-can-rsvp-to-an-event-748)

2023-03-15 19:56 UTC, tylerpar99 requested changes
I think if we are going to disable the button we should tell the user why, if not they might think the site is broken. Also, if I inspect the page and delete the `disabled` tag on the HTML button I can just RSVP anyway so we need to block them in `.js` or `.py`.

2023-03-15 20:01 UTC, tylerpar99 commented
This PR is good, just waiting on a companion PR that will fix some vulnerabilities. This PR should be left as is and will be merged with the branched PR.

2023-04-05 20:03 UTC, qasema commented
looks good, and agree with Tyler regarding the button being disabled

2023-04-14 18:45 UTC, Karina-Agliullova commented
While testing the PR, I noticed that I could select a negative number of people attending the event. I don't think it makes sense to go negative when setting the attendance limit

2023-04-14 20:24 UTC, Karina-Agliullova commented on tests/code/test_events.py
> +                        'rsvpLimit': None,
Why is newEventData{} implemented twice?

2023-05-10 13:46 UTC, closed without merging