Add a student's major and class level to the User table
BCStudentSoftwareDevTeam/celts pull request #855
Opened 2023-03-27 15:28 UTC by sreynit02

Fixes issue #854 
Did: 
- added "major" and "classLevel" to User table
- configure import_users.py so it can pull these two information from Tracy to our database

Test: 
- reset database
- update the Tracy password in config/default.yaml (ask Brian or Sreynit or Fleur for password)
- In database run 'python import_users.py'
- Check the User table. "major and classLevel" for students should be populated with their major and class level.

2023-03-29 13:34 UTC, Andersonstettner requested changes
add pyodbc to requirements.txt and the students who are in base data are not being updated correctly. 
EX: I changed Sreynit's name to just Sr, re-ran import_users and it fixed the name but still did not add a class level or major, it is like that for all students in base data.

2023-03-29 15:19 UTC, sreynit02 commented
> add pyodbc to requirements.txt and the students who are in base data are not being updated correctly. EX: I changed Sreynit's name to just Sr, re-ran import_users and it fixed the name but still did not add a class level or major, it is like that for all students in base data.

fixed!

2023-03-29 15:26 UTC, Andersonstettner requested changes
Nevermind, I went ahead and made the change since it was so small, everything looks good!

2023-04-10 14:41 UTC, Andersonstettner approved these changes

2023-04-10 14:41 UTC, merged