Rsvp and volunteer refactor
BCStudentSoftwareDevTeam/celts pull request #885
Opened 2023-05-15 14:16 UTC by Andersonstettner

2023-05-15 14:18 UTC, Andersonstettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to limit the number of volunteers that can RSVP to an event. #748](https://trello.com/c/HsFbG9aG/541-add-the-ability-to-limit-the-number-of-volunteers-that-can-rsvp-to-an-event-748)

2023-06-07 17:34 UTC, BrianRamsay requested changes

2023-06-07 17:34 UTC, BrianRamsay commented on app/controllers/admin/volunteers.py
> +        print(f"No event found for {eventID}", e)
I wouldn't output the exception. We know it is a DoesNotExist exception and it's only going to be thrown by one line so it is obvious. Outputting the other message is sufficient so we know which one wasn't found

2023-06-15 14:08 UTC, BrianRamsay approved these changes

2023-06-15 14:09 UTC, merged