making the drop down disappear when the bonner button is checked
BCStudentSoftwareDevTeam/celts pull request #931
Opened 2023-06-14 17:29 UTC by doucoureb

2023-06-16 14:25 UTC, AndersonStettner requested changes
The location/position of the footer have been a bit messed up. I have put screenshots below that show how it looks on your branch and how it looks on development. This is probably caused by a missing <div> or </div> tag somewhere. 

Your Branch:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/9c929319-7d73-407d-a950-2a11da67812a)


Development:
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/3a65a977-4ef6-44fe-b5f0-1e11b28f6bd6)

2023-06-16 18:31 UTC, BrianRamsay requested changes
We want to make sure that setting a bonner note ignores the visibility setting. Possibly this will mean adding a new visibility setting only applicable to bonner notes.

2023-06-16 18:31 UTC, BrianRamsay commented on app/static/js/userProfile.js
> +    $("#noteDrop").addClass('d-none')
Let's be consistent with `hide()` and `show()` everywhere instead of `removeClass` and `addClass`

2023-06-16 18:31 UTC, BrianRamsay commented on app/static/js/userProfile.js
> +    console.log(bonnerChecked)
remove debug output

2023-06-16 18:31 UTC, BrianRamsay commented on app/templates/main/userProfile.html
> +              <label class="form-label d-none" for='inputEventTerm' id="noteDrop"><strong>Bonner notes are visible to the students and admins</strong></label>
This message should be more like "This note will only be visible to Ebenezer and CELTS administrators."

2023-06-16 18:33 UTC, BrianRamsay commented
We also need to address the behavior when we click the Add Bonner Note button. The modal should only have the visibility message and the note field.

2023-06-20 16:02 UTC, AndersonStettner requested changes

2023-06-20 16:02 UTC, AndersonStettner commented on app/templates/main/userProfile.html
> +              <label class="form-label d-none" for='inputEventTerm' id="noteDrop"><strong>Bonner notes are visible to the students and admins</strong></label>
Add a period to the end of the sentence.

2023-06-20 16:02 UTC, AndersonStettner commented on app/templates/main/userProfile.html
> +              <label class="form-label {{vis}}" for='inputEventTerm' id="noteD"><strong>Visibility</strong></label>
Personally, I am not a fan of the id names given to this label or the previous label (`noteD` and `noteDrop`). I would prefer for them to be more descriptive of what they are actually an id of.

2023-06-20 16:02 UTC, AndersonStettner commented on app/templates/main/userProfile.html
> +              <div>
This hanging div might be responsible for the messed up footer.

2023-07-10 14:15 UTC, AndersonStettner requested changes

2023-07-10 14:15 UTC, AndersonStettner commented on app/static/js/userProfile.js
> +    $("#VisibilityLabel").hide()
We should be contestant with our naming, the v in `VisibilityLabel` should be lowercase.

2023-07-10 15:44 UTC, AndersonStettner approved these changes

2023-07-12 16:16 UTC, AndersonStettner requested changes
When "For Bonner" is checked, we want to ignore all the other note visibility options.

2023-07-12 16:30 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Hide all other visibility options when creating notes if "Related to Bonner..." is checked #901](https://trello.com/c/TEfahxW8/626-hide-all-other-visibility-options-when-creating-notes-if-related-to-bonner-is-checked-901)

2023-07-17 20:05 UTC, merged