Allow the creator of the Course Proposal to renew it
BCStudentSoftwareDevTeam/celts pull request #937
Opened 2023-06-15 19:15 UTC by stevensonmichel

Check whether the current user has created the course and allow him to renew a Course Proposal.
We were unable to recreate the bug where faculty members could not renew proposals for which they were among the faculty. 
This feature was working properly and looks fine in the code. 

Resolves #891

2023-06-16 14:18 UTC, AndersonStettner requested changes
Good work fixing the unauthorized part of the issue. The first part, "Renewal Unsuccessful" error, is still repeatable on my end. It occurs when a faculty member hits the `Renew` button before selecting a term from the `Select Term` drop-down.

2023-06-16 14:39 UTC, BrianRamsay approved these changes, later dismissed

2023-06-16 21:02 UTC, hoerstl commented
We've finished fixing all of the noted issues. We are ready to be pulled.

Resolves #891

2023-06-20 14:07 UTC, AndersonStettner requested changes

2023-06-20 14:07 UTC, AndersonStettner commented on app/static/js/slcManagement.js
> +      console.log("This should enable the thing!")
Remove debug code.

2023-06-20 14:07 UTC, AndersonStettner commented on app/templates/serviceLearning/slcManagement.html
> +                <td id="rMFacultyCell"></td>
Change to add a bit of specificity.

2023-06-20 15:01 UTC, hoerstl commented
This branch resolves #890 and also resolves #891.

2023-06-20 15:14 UTC, AndersonStettner requested changes

2023-06-20 15:14 UTC, AndersonStettner commented on app/templates/serviceLearning/slcManagement.html
> +  <input id="courseID" type="hidden" value="">
What is the point of the empty value?

2023-06-20 15:14 UTC, AndersonStettner commented on app/templates/serviceLearning/slcManagement.html
> +        <button type="button" class="btn btn-primary" id="withdrawBtn" onclick="withdraw()">Withdraw</button>
Why did you add the onclick?

2023-06-21 13:27 UTC, AndersonStettner approved these changes

2023-06-21 13:29 UTC, merged