896 dietary restrictions page
BCStudentSoftwareDevTeam/celts pull request #938
Opened 2023-06-16 14:12 UTC by andersoncedu

Added dietary restrictions page and added a link to dietary restrictions page to event list sub-pages.

2023-06-16 18:40 UTC, AndersonStettner requested changes
The following error happens when there is a user in the wait-list: 
![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/e42685f9-be06-44ec-ba1b-f534d22d3a3f)

This error occurs whether or not the RSVPd user or the wait-listed user have dietary restrictions.

2023-06-21 14:16 UTC, AndersonStettner requested changes
I got the following error when I tried to go to the dietary restrictions page:

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/6324077b-03b6-410c-91ac-60f52c579a28)


![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/f35fbbd7-97d6-4748-92c0-6bd5f7f92e99)

2023-06-22 13:04 UTC, AndersonStettner requested changes

2023-06-22 13:04 UTC, AndersonStettner commented on app/templates/events/dietary_restrictions.html
> +            <td class="col-auto" nowrap>>{{participant.firstName}} {{participant.lastName}}</td>
Is the extra > on purpose? If so what is it for?

2023-06-22 13:28 UTC, AndersonStettner requested changes

2023-06-22 13:28 UTC, AndersonStettner commented on app/controllers/admin/volunteers.py
> +def dietaryRestrictionsPage(eventID):
Access should be restricted to admin and student staff

2023-06-23 12:00 UTC, andersoncedu commented on app/templates/events/dietary_restrictions.html
> +            <td class="col-auto" nowrap>>{{participant.firstName}} {{participant.lastName}}</td>
It was a typo.

2023-06-23 15:32 UTC, AndersonStettner requested changes
There should not be so much space between the name and the dietary restriction:  

![image](https://github.com/BCStudentSoftwareDevTeam/celts/assets/26262045/737a6d54-5435-46d4-a504-f2ab7b8b2a75)

2023-06-28 15:00 UTC, AndersonStettner requested changes
Since we do not show the Waitlist after an event is in the past, we should not show those on the Waitlist in the Dietary Restrictions page. It should only have event participants at that point.

2023-06-28 15:00 UTC, AndersonStettner commented on app/templates/events/dietaryRestrictions.html
> +  <h3>Wait List</h3>
Wait List should be Waitlist.

2023-06-28 17:47 UTC, AndersonStettner approved these changes

2023-06-28 17:47 UTC, merged