improved the ids
BCStudentSoftwareDevTeam/celts pull request #939
Opened 2023-06-16 15:08 UTC by azabeli

2023-06-16 17:01 UTC, AndersonStettner requested changes
These are a good start but I think it would be good to be a bit more descriptive in the id names. For something like renaming a table it might be good to name the id based off of whatever information that table is showing.

2023-07-03 16:55 UTC, BrianRamsay requested changes
We should review more html than just the examples that Zach provided.

2023-07-03 16:55 UTC, BrianRamsay commented on app/templates/events/trackVolunteers.html
> +        <h5 class="modal-title" id="ModalLabel">{{modalTitle}}</h5>
If the id is never used, it doesn't need to be there at all.

2023-07-12 16:21 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improve Id Usage #564](https://trello.com/c/cDs9GSJ6/430-improve-id-usage-564)

2023-07-13 15:44 UTC, AndersonStettner requested changes
Resolve the merge conflicts.

2023-07-19 14:43 UTC, BrianRamsay approved these changes, later dismissed

2023-07-19 15:00 UTC, merged