Add participants
BCStudentSoftwareDevTeam/celts pull request #965
Opened 2023-06-27 14:02 UTC by doucoureb

2023-06-27 14:26 UTC, AndersonStettner requested changes

2023-06-27 14:26 UTC, AndersonStettner commented on app/controllers/events/routes.py
> +        kioskUser, userStatus = sendUserData(userObj.bnumber, eventid, programid)
This should have stayed `bnumber`.

2023-07-03 16:50 UTC, BrianRamsay approved these changes

2023-07-03 16:50 UTC, BrianRamsay commented on app/logic/participants.py
> +#                 EventParticipant.create(user = user, event = event, hoursEarned = eventHours)
Remove the comments that aren't being used, please

2023-07-03 16:52 UTC, BrianRamsay requested changes
As part of this refactor we should rename `sendUserData` to a meaningful name.

2023-07-05 16:07 UTC, BrianRamsay commented
I did this another way in PR #973

2023-07-05 16:07 UTC, closed without merging