Added RSVP Logs Tab to All Events
BCStudentSoftwareDevTeam/celts pull request #966
Opened 2023-06-27 18:42 UTC by hoerstl

We added another tab to all event pages. It displays the history of all RSVPs and waitlist actions that have been taken by admins or by the students themselves. 

Resolves #829

2023-06-28 18:17 UTC, AndersonStettner requested changes
Resolve merge conflict

2023-06-28 18:17 UTC, AndersonStettner commented on app/templates/events/rsvpLog.html
> +  {#Todo: Make new js file#}
remove Todo if it is done. Do it if it is not done.

2023-06-29 13:37 UTC, AndersonStettner requested changes

2023-06-29 13:37 UTC, AndersonStettner commented on app/controllers/admin/routes.py
> +        allLogs = EventRsvpLogs.select(EventRsvpLogs, User).join(User).order_by(EventRsvpLogs.createdOn.desc()).where(EventRsvpLogs.event_id == eventId)
We should move the `.order_by` to the end. To paraphrase Brian, "Always put your `.order_by` and `.group_by` at the end of the query.

2023-07-03 16:32 UTC, BrianRamsay requested changes

2023-07-03 16:32 UTC, BrianRamsay commented on app/controllers/main/routes.py
> +        createAdminLog(f'Banned {username} from {programInfo.programName} until {banEndDate}.')
You never import `createAdminLog`

2023-07-05 14:14 UTC, BrianRamsay requested changes

2023-07-05 14:14 UTC, BrianRamsay commented on app/models/eventRsvpLogs.py
> +class EventRsvpLogs(baseModel):
Class and table names should be singular, as each record is a single log

2023-07-05 14:41 UTC, BrianRamsay approved these changes

2023-07-05 14:41 UTC, merged