Mobile kiosk mode
BCStudentSoftwareDevTeam/celts pull request #977
Opened 2023-07-10 13:25 UTC by Mercy-Eze

Barcode function works (literally)... but not technically
Outputs False Positives

2023-07-12 16:33 UTC, AndersonStettner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to use kiosk mode form a mobile phone, use camera to capture barcode on IDs #812](https://trello.com/c/99d5seQZ/583-add-the-ability-to-use-kiosk-mode-form-a-mobile-phone-use-camera-to-capture-barcode-on-ids-812)

2023-07-28 19:20 UTC, BrianRamsay requested changes
1. You still have to hit the camera button twice to bring up the camera
2. Let's make the camera button a little larger (side padding)
3. The placeholder text is cut off on my phone "Enter scanner da". I'd change it to something like Enter B-Number or B# anyway.
4. Using the full screen option hides the camera button
5. Sometimes the camera button is the same width as the input box and below it, and sometimes it is small on the right. We should be consistent.

2023-07-28 19:20 UTC, BrianRamsay commented on app/templates/base.html
> +  <script src="https://cdn.jsdelivr.net/npm/quagga/dist/quagga.min.js"></script>
we aren't using quagga anymore

2023-07-28 19:20 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +
Let's leave some comments in this section that explain what the pieces do

2023-07-31 18:10 UTC, AndersonStettner requested changes
Make sure to handle the same person being added multiple times.

2023-07-31 19:51 UTC, zachneill requested changes
var is gonna be deprecated one day

2023-07-31 19:51 UTC, zachneill commented on app/static/js/eventKiosk.js
> +  var lastResult, countResults = 0;
hey dont use var again

2023-07-31 19:51 UTC, zachneill commented on app/static/js/eventKiosk.js
> +  var html5QrcodeScanner = new Html5QrcodeScanner(
gah you used var again

2023-08-01 15:50 UTC, BrianRamsay requested changes

2023-08-01 15:50 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +      ;
What does this do?

2023-08-01 15:50 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +  function onScanSuccess(decodedText, decodedResult) {
I would add a check to make sure we have a full b-number, to avoid submitting that case where it scanned a partial one

2023-08-01 15:50 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +      success: function(decodedText) {
what is passed into this function is not decoded text. If you are going to rename it from result, name it something more meaningful.

2023-08-01 15:50 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +          console.log(`Scan result ${decodedText}`, decodedResult);
Remove debug output

2023-08-01 15:50 UTC, BrianRamsay commented on app/static/js/eventKiosk.js
> +          ++countResults;
You don't use `countResults`

2023-08-04 15:55 UTC, AndersonStettner requested changes

2023-08-04 15:55 UTC, AndersonStettner commented on app/static/js/eventKiosk.js
> +          console.log(`Scan result ${decodedText}`, decodedResult);
Remove debug output

2023-08-04 15:55 UTC, AndersonStettner commented on app/static/js/eventKiosk.js
> +    console.log('id code', decodedText)
Remove debug output

2023-08-04 15:55 UTC, AndersonStettner commented on app/static/js/eventKiosk.js
> +        console.log("Invalid B-number:", decodedText);
Remove debug output

2023-08-08 20:44 UTC, BrianRamsay approved these changes

2023-08-08 20:44 UTC, merged